-- Wenmang progress, v1 of the schema.
--
-- The shape here is deliberately inverted from the way the browser stores
-- progress. `reviews` is an append-only log and is the source of truth;
-- `cards` is a fold over it and can be dropped and rebuilt at any time.
--
-- That inversion is the whole point. A new statistic can always be derived
-- from an event log, but history that was never written cannot be recovered.
-- It is what makes changing the scheduling algorithm later a re-fold rather
-- than a reset, and it is what lets two devices merge without a conflict:
-- the log is a set union and the fold is deterministic.
--
-- Everything about an item carries a `kind`. A word card ("do you know what
-- 苹果 means") and a character card ("can you write 苹") are different skills
-- with different schedules, and merging them would let reading progress report
-- itself as handwriting ability. They share these tables because they share
-- every column; only the fold differs, and the fold lives in code.

CREATE TABLE IF NOT EXISTS users (
    id            TEXT PRIMARY KEY,           -- 'google:<sub>'
    provider      TEXT NOT NULL,
    provider_id   TEXT NOT NULL,
    display_name  TEXT NOT NULL,
    created_at    INTEGER NOT NULL,
    UNIQUE (provider, provider_id)
);

-- Append-only. Never UPDATEd, never DELETEd.
--
-- `id` is generated by the client, so a retried or duplicated upload collides
-- on the primary key and is ignored rather than double-counted.
--
-- `item` is the progress key the browser already uses: the Chinese word for a
-- word review, the single character for a writing one. Deliberately not a
-- foreign key — the word list lives in a static file, and a words table would
-- have to be re-synced on every deploy.
--
-- `mode` is what makes a character review foldable. A character's box depends
-- on whether it was traced or written from a blank pad, so replaying its
-- history means replaying the caps; without the mode on the row, the server
-- could only guess, and would guess in the direction that flatters the learner.
CREATE TABLE IF NOT EXISTS reviews (
    id           TEXT PRIMARY KEY,
    user_id      TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    kind         TEXT NOT NULL,               -- 'word' | 'char'
    item         TEXT NOT NULL,
    deck_id      TEXT,                        -- where the answer happened: context,
    stage        INTEGER,                     -- not identity. An item is one card no
    direction    TEXT,                        -- matter where it was met.
    mode         TEXT,                        -- writing mode, for kind = 'char'
    correct      INTEGER NOT NULL,
    reviewed_at  INTEGER NOT NULL,            -- client clock, ms
    received_at  INTEGER NOT NULL,            -- server clock, ms — catches a skewed device
    source       TEXT NOT NULL DEFAULT 'review',
    srs_version  INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reviews_fold   ON reviews (user_id, kind, item, reviewed_at);
CREATE INDEX IF NOT EXISTS idx_reviews_recent ON reviews (user_id, reviewed_at DESC);

-- Derived from `reviews`. Kept only so the first load after sign-in is one
-- indexed read instead of a fold over everything.
CREATE TABLE IF NOT EXISTS cards (
    user_id      TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    kind         TEXT NOT NULL,
    item         TEXT NOT NULL,
    box          INTEGER NOT NULL,
    due_at       INTEGER NOT NULL,            -- a timestamp, not a question counter
    seen         INTEGER NOT NULL,
    correct      INTEGER NOT NULL,
    last_seen_at INTEGER NOT NULL,
    srs_version  INTEGER NOT NULL,
    updated_at   INTEGER NOT NULL,
    PRIMARY KEY (user_id, kind, item)
);

CREATE INDEX IF NOT EXISTS idx_cards_changed ON cards (user_id, updated_at);

-- The starting card for an item, for somebody who had progress in a browser
-- before they had an account.
--
-- Deliberately not written into `reviews`. The browser never recorded how that
-- progress was earned — only where it ended up — and inventing a plausible
-- history to match would be a lie every statistic built on the log would then
-- repeat. A seed is honest about being a snapshot.
CREATE TABLE IF NOT EXISTS imports (
    user_id      TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    kind         TEXT NOT NULL,
    item         TEXT NOT NULL,
    box          INTEGER NOT NULL,
    due_at       INTEGER NOT NULL,
    seen         INTEGER NOT NULL,
    correct      INTEGER NOT NULL,
    last_seen_at INTEGER NOT NULL,
    imported_at  INTEGER NOT NULL,
    PRIMARY KEY (user_id, kind, item)
);

-- A round is a UI concept and can be abandoned half-finished, so it does not
-- belong in `reviews`. Personal history only — nothing here ranks one learner
-- against another.
--
-- `local_day` is the learner's own calendar date, stamped by their browser and
-- stored as an opaque string. Someone playing at nine in the evening in
-- California is having a Tuesday; a streak computed from a UTC timestamp would
-- file it under Wednesday and break their streak while they did everything
-- right. It also makes crossing a date line harmless.
CREATE TABLE IF NOT EXISTS rounds (
    id          TEXT PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type        TEXT NOT NULL,                -- 'words' | 'characters'
    deck_id     TEXT NOT NULL,
    stages      TEXT NOT NULL,
    direction   TEXT NOT NULL,
    asked       INTEGER NOT NULL,
    correct     INTEGER NOT NULL,
    started_at  INTEGER NOT NULL,
    ended_at    INTEGER NOT NULL,
    local_day   TEXT
);

CREATE INDEX IF NOT EXISTS idx_rounds_day ON rounds (user_id, local_day);

-- Manual streak-guard changes: pausing for a holiday, and resuming after.
--
-- A log rather than a state column, for the same reason cards are a fold over
-- reviews. A column is something two devices can disagree about and nothing can
-- repair; a log keyed by a client-made id merges by set union and folds to one
-- answer wherever it is read.
CREATE TABLE IF NOT EXISTS guards (
    id         TEXT PRIMARY KEY,
    user_id    TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    day        TEXT NOT NULL,
    at         INTEGER NOT NULL,
    state      TEXT NOT NULL,
    source     TEXT NOT NULL DEFAULT 'manual',
    created_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_guards_user ON guards (user_id, day, at);

-- The handful of per-user scalars that are not per-item.
CREATE TABLE IF NOT EXISTS profiles (
    user_id   TEXT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    synced_at INTEGER NOT NULL DEFAULT 0
);
