// The 214 Kangxi radicals, which is the vocabulary the hint ladder speaks in.
//
// Unihan tells us a character's radical *by number*; a learner needs the shape,
// its name, and what it means. That last part is the whole reason radicals are
// worth teaching: 妈 姐 妹 奶 娘 all carry 女, and once you have seen that once
// you never again meet those characters as unrelated squiggles.
//
// Each row is [traditional form, simplified form or null, combining variants,
// pinyin, meaning]. A tuple rather than an object purely because there are 214
// of them and the shape never varies; RADICALS below gives them names.
//
// Variants are the forms a radical takes when it is squeezed into a character —
// 人 becomes 亻 on the left, 水 becomes 氵, 心 becomes 忄. These matter more
// than the citation form, since the variant is what actually appears in the
// characters being learned.
//
// The meanings are glosses, not translations: a radical is a hint about a
// character's domain, not a word. 攵 is not "the word rap"; it is the mark of
// an action done to something.

const ROWS = [
  ['一', null, '', 'yī', 'one'],
  ['丨', null, '', 'gǔn', 'line'],
  ['丶', null, '', 'zhǔ', 'dot'],
  ['丿', null, '', 'piě', 'slash'],
  ['乙', null, '乚乛', 'yǐ', 'second'],
  ['亅', null, '', 'jué', 'hook'],
  ['二', null, '', 'èr', 'two'],
  ['亠', null, '', 'tóu', 'lid'],
  ['人', null, '亻', 'rén', 'person'],
  ['儿', null, '', 'ér', 'legs'],
  ['入', null, '', 'rù', 'enter'],
  ['八', null, '丷', 'bā', 'eight'],
  ['冂', null, '', 'jiōng', 'open box'],
  ['冖', null, '', 'mì', 'cover'],
  ['冫', null, '', 'bīng', 'ice'],
  ['几', null, '', 'jī', 'table'],
  ['凵', null, '', 'kǎn', 'open box'],
  ['刀', null, '刂⺈', 'dāo', 'knife'],
  ['力', null, '', 'lì', 'power'],
  ['勹', null, '', 'bāo', 'wrap'],
  ['匕', null, '', 'bǐ', 'spoon'],
  ['匚', null, '', 'fāng', 'box'],
  ['匸', null, '', 'xǐ', 'hiding'],
  ['十', null, '', 'shí', 'ten'],
  ['卜', null, '', 'bǔ', 'divination'],
  ['卩', null, '㔾', 'jié', 'seal'],
  ['厂', null, '', 'hǎn', 'cliff'],
  ['厶', null, '', 'sī', 'private'],
  ['又', null, '', 'yòu', 'again'],
  ['口', null, '', 'kǒu', 'mouth'],
  ['囗', null, '', 'wéi', 'enclosure'],
  ['土', null, '', 'tǔ', 'earth'],
  ['士', null, '', 'shì', 'scholar'],
  ['夂', null, '', 'zhǐ', 'go'],
  ['夊', null, '', 'suī', 'go slowly'],
  ['夕', null, '', 'xī', 'evening'],
  ['大', null, '', 'dà', 'big'],
  ['女', null, '', 'nǚ', 'woman'],
  ['子', null, '', 'zǐ', 'child'],
  ['宀', null, '', 'mián', 'roof'],
  ['寸', null, '', 'cùn', 'inch'],
  ['小', null, '⺌⺍', 'xiǎo', 'small'],
  ['尢', null, '尣', 'wāng', 'lame'],
  ['尸', null, '', 'shī', 'corpse'],
  ['屮', null, '', 'chè', 'sprout'],
  ['山', null, '', 'shān', 'mountain'],
  ['巛', null, '川', 'chuān', 'river'],
  ['工', null, '', 'gōng', 'work'],
  ['己', null, '巳已', 'jǐ', 'oneself'],
  ['巾', null, '', 'jīn', 'turban'],
  ['干', null, '', 'gān', 'dry'],
  ['幺', null, '', 'yāo', 'short thread'],
  ['广', null, '', 'yǎn', 'dotted cliff'],
  ['廴', null, '', 'yǐn', 'long stride'],
  ['廾', null, '', 'gǒng', 'two hands'],
  ['弋', null, '', 'yì', 'shoot'],
  ['弓', null, '', 'gōng', 'bow'],
  ['彐', null, '彑', 'jì', 'snout'],
  ['彡', null, '', 'shān', 'bristle'],
  ['彳', null, '', 'chì', 'step'],
  ['心', null, '忄⺗', 'xīn', 'heart'],
  ['戈', null, '', 'gē', 'halberd'],
  ['戶', '户', '戸', 'hù', 'door'],
  ['手', null, '扌', 'shǒu', 'hand'],
  ['支', null, '', 'zhī', 'branch'],
  ['攴', null, '攵', 'pū', 'action done to'],
  ['文', null, '', 'wén', 'script'],
  ['斗', null, '', 'dǒu', 'dipper'],
  ['斤', null, '', 'jīn', 'axe'],
  ['方', null, '', 'fāng', 'square'],
  ['无', null, '旡', 'wú', 'not'],
  ['日', null, '', 'rì', 'sun'],
  ['曰', null, '', 'yuē', 'say'],
  ['月', null, '', 'yuè', 'moon'],
  ['木', null, '', 'mù', 'tree'],
  ['欠', null, '', 'qiàn', 'lack'],
  ['止', null, '', 'zhǐ', 'stop'],
  ['歹', null, '歺', 'dǎi', 'death'],
  ['殳', null, '', 'shū', 'weapon'],
  ['毋', null, '母', 'wú', 'do not'],
  ['比', null, '', 'bǐ', 'compare'],
  ['毛', null, '', 'máo', 'fur'],
  ['氏', null, '', 'shì', 'clan'],
  ['气', null, '', 'qì', 'steam'],
  ['水', null, '氵氺', 'shuǐ', 'water'],
  ['火', null, '灬', 'huǒ', 'fire'],
  ['爪', null, '爫', 'zhǎo', 'claw'],
  ['父', null, '', 'fù', 'father'],
  ['爻', null, '', 'yáo', 'trigrams'],
  ['爿', null, '丬', 'qiáng', 'split wood'],
  ['片', null, '', 'piàn', 'slice'],
  ['牙', null, '', 'yá', 'fang'],
  ['牛', null, '牜', 'niú', 'cow'],
  ['犬', null, '犭', 'quǎn', 'dog'],
  ['玄', null, '', 'xuán', 'profound'],
  ['玉', null, '王', 'yù', 'jade'],
  ['瓜', null, '', 'guā', 'melon'],
  ['瓦', null, '', 'wǎ', 'tile'],
  ['甘', null, '', 'gān', 'sweet'],
  ['生', null, '', 'shēng', 'life'],
  ['用', null, '', 'yòng', 'use'],
  ['田', null, '', 'tián', 'field'],
  ['疋', null, '⺪', 'pǐ', 'bolt of cloth'],
  ['疒', null, '', 'chuáng', 'sickness'],
  ['癶', null, '', 'bō', 'footsteps'],
  ['白', null, '', 'bái', 'white'],
  ['皮', null, '', 'pí', 'skin'],
  ['皿', null, '', 'mǐn', 'dish'],
  ['目', null, '', 'mù', 'eye'],
  ['矛', null, '', 'máo', 'spear'],
  ['矢', null, '', 'shǐ', 'arrow'],
  ['石', null, '', 'shí', 'stone'],
  ['示', null, '礻', 'shì', 'spirit'],
  ['禸', null, '', 'róu', 'track'],
  ['禾', null, '', 'hé', 'grain'],
  ['穴', null, '', 'xué', 'cave'],
  ['立', null, '', 'lì', 'stand'],
  ['竹', null, '⺮', 'zhú', 'bamboo'],
  ['米', null, '', 'mǐ', 'rice'],
  ['糸', '纟', '糹', 'mì', 'silk'],
  ['缶', null, '', 'fǒu', 'jar'],
  ['网', null, '罒⺆', 'wǎng', 'net'],
  ['羊', null, '⺶⺷', 'yáng', 'sheep'],
  ['羽', null, '', 'yǔ', 'feather'],
  ['老', null, '耂', 'lǎo', 'old'],
  ['而', null, '', 'ér', 'and'],
  ['耒', null, '', 'lěi', 'plow'],
  ['耳', null, '', 'ěr', 'ear'],
  ['聿', null, '⺻', 'yù', 'brush'],
  ['肉', null, '月', 'ròu', 'meat'],
  ['臣', null, '', 'chén', 'minister'],
  ['自', null, '', 'zì', 'self'],
  ['至', null, '', 'zhì', 'arrive'],
  ['臼', null, '', 'jiù', 'mortar'],
  ['舌', null, '', 'shé', 'tongue'],
  ['舛', null, '', 'chuǎn', 'oppose'],
  ['舟', null, '', 'zhōu', 'boat'],
  ['艮', null, '', 'gèn', 'stopping'],
  ['色', null, '', 'sè', 'color'],
  ['艸', '艹', '艹', 'cǎo', 'grass'],
  ['虍', null, '', 'hū', 'tiger'],
  ['虫', null, '', 'chóng', 'insect'],
  ['血', null, '', 'xuè', 'blood'],
  ['行', null, '', 'xíng', 'walk'],
  ['衣', null, '衤', 'yī', 'clothes'],
  ['襾', null, '西覀', 'yà', 'cover'],
  ['見', '见', '', 'jiàn', 'see'],
  ['角', null, '', 'jiǎo', 'horn'],
  ['言', null, '讠', 'yán', 'speech'],
  ['谷', null, '', 'gǔ', 'valley'],
  ['豆', null, '', 'dòu', 'bean'],
  ['豕', null, '', 'shǐ', 'pig'],
  ['豸', null, '', 'zhì', 'badger'],
  ['貝', '贝', '', 'bèi', 'shell, money'],
  ['赤', null, '', 'chì', 'red'],
  ['走', null, '', 'zǒu', 'run'],
  ['足', null, '⻊', 'zú', 'foot'],
  ['身', null, '', 'shēn', 'body'],
  ['車', '车', '', 'chē', 'cart'],
  ['辛', null, '', 'xīn', 'bitter'],
  ['辰', null, '', 'chén', 'morning'],
  ['辵', '辶', '辶', 'chuò', 'movement'],
  ['邑', null, '阝', 'yì', 'city'],
  ['酉', null, '', 'yǒu', 'wine'],
  ['釆', null, '', 'biàn', 'distinguish'],
  ['里', null, '', 'lǐ', 'village'],
  ['金', null, '钅', 'jīn', 'metal'],
  ['長', '长', '镸', 'cháng', 'long'],
  ['門', '门', '', 'mén', 'gate'],
  ['阜', null, '阝', 'fù', 'mound'],
  ['隶', null, '', 'dài', 'slave'],
  ['隹', null, '', 'zhuī', 'short-tailed bird'],
  ['雨', null, '', 'yǔ', 'rain'],
  ['青', null, '靑', 'qīng', 'blue-green'],
  ['非', null, '', 'fēi', 'wrong'],
  ['面', null, '', 'miàn', 'face'],
  ['革', null, '', 'gé', 'leather'],
  ['韋', '韦', '', 'wéi', 'tanned leather'],
  ['韭', null, '', 'jiǔ', 'leek'],
  ['音', null, '', 'yīn', 'sound'],
  ['頁', '页', '', 'yè', 'page'],
  ['風', '风', '', 'fēng', 'wind'],
  ['飛', '飞', '', 'fēi', 'fly'],
  ['食', null, '饣飠', 'shí', 'eat'],
  ['首', null, '', 'shǒu', 'head'],
  ['香', null, '', 'xiāng', 'fragrant'],
  ['馬', '马', '', 'mǎ', 'horse'],
  ['骨', null, '', 'gǔ', 'bone'],
  ['高', null, '', 'gāo', 'tall'],
  ['髟', null, '', 'biāo', 'long hair'],
  ['鬥', '斗', '', 'dòu', 'fight'],
  ['鬯', null, '', 'chàng', 'sacrificial wine'],
  ['鬲', null, '', 'lì', 'cauldron'],
  ['鬼', null, '', 'guǐ', 'ghost'],
  ['魚', '鱼', '', 'yú', 'fish'],
  ['鳥', '鸟', '', 'niǎo', 'bird'],
  ['鹵', '卤', '', 'lǔ', 'salt'],
  ['鹿', null, '', 'lù', 'deer'],
  ['麥', '麦', '', 'mài', 'wheat'],
  ['麻', null, '', 'má', 'hemp'],
  ['黃', '黄', '', 'huáng', 'yellow'],
  ['黍', null, '', 'shǔ', 'millet'],
  ['黑', null, '', 'hēi', 'black'],
  ['黹', null, '', 'zhǐ', 'embroidery'],
  ['黽', '黾', '', 'mǐn', 'frog'],
  ['鼎', null, '', 'dǐng', 'tripod'],
  ['鼓', null, '', 'gǔ', 'drum'],
  ['鼠', null, '', 'shǔ', 'rat'],
  ['鼻', null, '', 'bí', 'nose'],
  ['齊', '齐', '', 'qí', 'even'],
  ['齒', '齿', '', 'chǐ', 'tooth'],
  ['龍', '龙', '', 'lóng', 'dragon'],
  ['龜', '龟', '', 'guī', 'turtle'],
  ['龠', null, '', 'yuè', 'flute']
];

/** Radical number (1..214) to its shapes and meaning. */
export const RADICALS = Object.fromEntries(
  ROWS.map(([char, simplified, variants, py, en], index) => [
    index + 1,
    {
      number: index + 1,
      char,
      simplified,
      variants: [...variants],
      py,
      en,
      /** What a learner should actually see: the simplified form when there is one. */
      display: simplified ?? char
    }
  ])
);

export const RADICAL_COUNT = ROWS.length;

export function getRadical(number) {
  return RADICALS[number] ?? null;
}

/**
 * Every shape this radical can appear as, citation form first. Used to spot the
 * radical inside a character when we have no stroke-level data to point at.
 */
export function formsOf(number) {
  const radical = getRadical(number);
  if (!radical) return [];
  return [...new Set([radical.display, radical.char, ...radical.variants])];
}
