// One example sentence per word, with its English translation.
//
// Keyed by the Chinese headword exactly as it appears in vocab.js. That string
// is the progress key, so the join is the same one the rest of the app makes.
// A word with no entry here simply gets no example.
//
// Each pair is [Chinese, English]. The English translates the Chinese sentence
// rather than standing alone — the two are shown together, so they have to line
// up.
//
// Generated by tools/sentences.mjs and checked by it before being written: the
// sentence contains its headword, is between 4 and 22 characters, and carries
// no Latin letters. Regenerate with:
//
//   node tools/sentences.mjs --deck <id> --stage <n>
//
// NOT YET REVIEWED BY A NATIVE SPEAKER. The checks above are mechanical;
// whether a sentence is natural is not something they can tell you.

export const SENTENCES = {
};

/** The example for a word, or null. */
export function sentenceFor(zh) {
  return SENTENCES[zh] ?? null;
}
