// One example sentence per word: the Chinese, its pinyin, and its English.
//
// Keyed by the Chinese headword exactly as it appears in vocab.js. That string
// is the progress key, so the join is the same one the rest of the app makes.
// A word with no entry here simply gets no example.
//
// Each entry is [Chinese, pinyin, English]. The pinyin is the sentence read
// aloud, not a gloss — it follows the same script setting as the prompt, so a
// learner who has the toggle on pinyin gets the sentence in pinyin too. The
// English translates the Chinese rather than standing alone; the three are
// shown together and have to line up.
//
// House style, so a reviewer has something to hold these to:
//   - short: 4 to 22 characters, one clause or two
//   - natural: what a person would actually say, not a dictionary illustration
//   - the sentence disambiguates the word, which is the whole point of the
//     feature: 菜 in one sentence is a dish, in another it is a vegetable
//   - simplified characters, no Latin letters, no names
//   - no 他/她 where a neutral subject will do — a sentence should not need a
//     person invented for it
//   - pinyin with tone marks, spaced by word rather than by syllable, with
//     sandhi written as it is said: 一杯 is yì bēi, 不放 is bú fàng
//
// Written a deck at a time through tools/add-sentences.mjs, which rejects a
// batch whole rather than merging half of it, and checked by
// tools/check-vocab.mjs, which aligns every sentence's pinyin against the
// readings Unicode records for its characters. That is all mechanical. Whether
// a sentence is natural is not, and these have
//
// NOT YET BEEN REVIEWED BY A NATIVE SPEAKER.

export const SENTENCES = {
  '乌龟': ["乌龟走得很慢。", "wūguī zǒu de hěn màn", "Turtles walk very slowly."],
  '书架': ["书架上摆满了书。", "shūjià shàng bǎi mǎn le shū", "The bookshelf is full of books."],
  '仓库': ["旧家具放在仓库里。", "jiù jiājù fàng zài cāngkù lǐ", "The old furniture is kept in the storeroom."],
  '保护': ["我们要保护野生动物。", "wǒmen yào bǎohù yěshēng dòngwù", "We should protect wild animals."],
  '修理': ["空调坏了,得找人修理。", "kōngtiáo huài le, děi zhǎo rén xiūlǐ", "The air conditioner is broken and needs repairing."],
  '做': ["晚饭是我做的。", "wǎnfàn shì wǒ zuò de", "I made dinner."],
  '停': ["车停在门口。", "chē tíng zài ménkǒu", "The car is parked at the entrance."],
  '停电': ["昨天晚上停电了。", "zuótiān wǎnshang tíngdiàn le", "The power went out last night."],
  '兔子': ["兔子跑得很快。", "tùzi pǎo de hěn kuài", "Rabbits run fast."],
  '公寓': ["我们租了一套小公寓。", "wǒmen zū le yí tào xiǎo gōngyù", "We rented a small apartment."],
  '关': ["走的时候关灯。", "zǒu de shíhou guān dēng", "Turn the light off when you leave."],
  '兽医': ["我带猫去看兽医。", "wǒ dài māo qù kàn shòuyī", "I took the cat to see the vet."],
  '写': ["名字写在这里。", "míngzi xiě zài zhèlǐ", "Write your name here."],
  '冰箱': ["牛奶放在冰箱里。", "niúnǎi fàng zài bīngxiāng lǐ", "The milk is in the fridge."],
  '决定': ["我们还没决定。", "wǒmen hái méi juédìng", "We have not decided yet."],
  '准备': ["我们在准备晚饭。", "wǒmen zài zhǔnbèi wǎnfàn", "We are getting dinner ready."],
  '减少': ["最近开支减少了。", "zuìjìn kāizhī jiǎnshǎo le", "Spending has gone down recently."],
  '出': ["我出去一会儿。", "wǒ chūqù yíhuìr", "I am going out for a while."],
  '刀': ["这把刀不太快。", "zhè bǎ dāo bú tài kuài", "This knife is not very sharp."],
  '别墅': ["山上那栋别墅很贵。", "shān shàng nà dòng biéshù hěn guì", "That villa up on the hill is expensive."],
  '动物': ["动物园里有很多动物。", "dòngwùyuán lǐ yǒu hěn duō dòngwù", "There are many animals in the zoo."],
  '动物园': ["周末我们去动物园。", "zhōumò wǒmen qù dòngwùyuán", "We are going to the zoo at the weekend."],
  '勺子': ["喝汤要用勺子。", "hē tāng yào yòng sháozi", "You need a spoon for soup."],
  '包子': ["早上买了两个包子。", "zǎoshang mǎi le liǎng gè bāozi", "I bought two steamed buns this morning."],
  '包括': ["价格包括早饭。", "jiàgé bāokuò zǎofàn", "The price includes breakfast."],
  '午饭': ["我们中午一起吃午饭。", "wǒmen zhōngwǔ yìqǐ chī wǔfàn", "We eat lunch together at noon."],
  '卧室': ["卧室在楼上。", "wòshì zài lóushàng", "The bedroom is upstairs."],
  '厕所': ["请问厕所在哪里?", "qǐngwèn cèsuǒ zài nǎlǐ", "Excuse me, where is the toilet?"],
  '厨房': ["厨房里飘出饭菜的香味。", "chúfáng lǐ piāo chū fàncài de xiāngwèi", "The smell of cooking drifts out of the kitchen."],
  '去': ["下午我要去银行。", "xiàwǔ wǒ yào qù yínháng", "I need to go to the bank this afternoon."],
  '反对': ["有几个人反对。", "yǒu jǐ gè rén fǎnduì", "A few people are against it."],
  '发现': ["我发现钱包不见了。", "wǒ fāxiàn qiánbāo bú jiàn le", "I found that my wallet was gone."],
  '吃': ["你想吃什么？", "nǐ xiǎng chī shénme", "What do you want to eat?"],
  '否认': ["没人否认这件事。", "méi rén fǒurèn zhè jiàn shì", "Nobody denies this."],
  '听': ["路上我喜欢听音乐。", "lù shàng wǒ xǐhuan tīng yīnyuè", "I like listening to music on the way."],
  '味道': ["这道菜味道很好。", "zhè dào cài wèidào hěn hǎo", "This dish tastes very good."],
  '咖啡': ["这杯咖啡太苦了。", "zhè bēi kāfēi tài kǔ le", "This cup of coffee is too bitter."],
  '咬': ["那只狗不咬人。", "nà zhī gǒu bù yǎo rén", "That dog does not bite."],
  '咸': ["汤有点咸了。", "tāng yǒudiǎn xián le", "The soup has come out a bit salty."],
  '哺乳动物': ["鲸鱼是哺乳动物。", "jīngyú shì bǔrǔdòngwù", "The whale is a mammal."],
  '喂': ["别喂动物园的动物。", "bié wèi dòngwùyuán de dòngwù", "Do not feed the animals at the zoo."],
  '喜欢': ["我不太喜欢辣的。", "wǒ bú tài xǐhuan là de", "I do not much like spicy food."],
  '喝': ["睡前别喝咖啡。", "shuì qián bié hē kāfēi", "Don't drink coffee before bed."],
  '回': ["我八点回家。", "wǒ bā diǎn huí jiā", "I will be home at eight."],
  '回答': ["这个问题很难回答。", "zhège wèntí hěn nán huídá", "This question is hard to answer."],
  '土豆': ["土豆放久了会发芽。", "tǔdòu fàng jiǔ le huì fāyá", "Potatoes sprout if kept too long."],
  '地板': ["地板刚擦过,还湿着。", "dìbǎn gāng cā guò, hái shī zhe", "The floor was just mopped and is still wet."],
  '地毯': ["地毯上有块污渍。", "dìtǎn shàng yǒu kuài wūzì", "There is a stain on the carpet."],
  '坐': ["请坐在这边。", "qǐng zuò zài zhèbiān", "Please sit over here."],
  '坚持': ["坚持三个月就有效果。", "jiānchí sān gè yuè jiù yǒu xiàoguǒ", "Keep it up for three months and it works."],
  '墙': ["墙上挂着一幅画。", "qiáng shàng guà zhe yì fú huà", "A painting hangs on the wall."],
  '增加': ["今年学生增加了很多。", "jīnnián xuésheng zēngjiā le hěn duō", "The number of students has grown a lot this year."],
  '处理': ["这件事我来处理。", "zhè jiàn shì wǒ lái chǔlǐ", "I will handle this."],
  '大蒜': ["这道菜放了很多大蒜。", "zhè dào cài fàng le hěn duō dàsuàn", "This dish has a lot of garlic in it."],
  '大象': ["大象的鼻子很长。", "dàxiàng de bízi hěn cháng", "An elephant's trunk is very long."],
  '天花板': ["天花板上有裂缝。", "tiānhuābǎn shàng yǒu lièfèng", "There is a crack in the ceiling."],
  '好吃': ["这家的菜很好吃。", "zhè jiā de cài hěn hǎochī", "The food at this place is very tasty."],
  '学': ["我在学中文。", "wǒ zài xué Zhōngwén", "I am learning Chinese."],
  '孵化': ["鸡蛋还没孵化。", "jīdàn hái méi fūhuà", "The eggs have not hatched yet."],
  '安排': ["时间已经安排好了。", "shíjiān yǐjīng ānpái hǎo le", "The timing has already been arranged."],
  '完成': ["工作明天能完成。", "gōngzuò míngtiān néng wánchéng", "The work can be finished tomorrow."],
  '实现': ["这个目标很难实现。", "zhège mùbiāo hěn nán shíxiàn", "This goal is hard to achieve."],
  '宠物': ["我家养了两只宠物。", "wǒ jiā yǎng le liǎng zhī chǒngwù", "We keep two pets at home."],
  '客厅': ["客人都坐在客厅里。", "kèrén dōu zuò zài kètīng lǐ", "The guests are all sitting in the living room."],
  '家': ["我家离学校很近。", "wǒ jiā lí xuéxiào hěn jìn", "My home is close to the school."],
  '家具': ["这些家具都是新买的。", "zhèxiē jiājù dōu shì xīn mǎi de", "All this furniture was newly bought."],
  '宽敞': ["客厅又大又宽敞。", "kètīng yòu dà yòu kuānchang", "The living room is big and spacious."],
  '小鸡': ["小鸡跟着母鸡走。", "xiǎojī gēn zhe mǔjī zǒu", "The chicks follow the hen."],
  '尝': ["你尝尝这个汤。", "nǐ chángchang zhège tāng", "Have a taste of this soup."],
  '尾巴': ["那只猫的尾巴很长。", "nà zhī māo de wěiba hěn cháng", "That cat's tail is very long."],
  '屋顶': ["屋顶漏水了。", "wūdǐng lòushuǐ le", "The roof is leaking."],
  '巢': ["树上有个鸟巢。", "shù shàng yǒu gè niǎocháo", "There is a bird's nest in the tree."],
  '巧克力': ["这块巧克力有点苦。", "zhè kuài qiǎokèlì yǒudiǎn kǔ", "This chocolate is a little bitter."],
  '希望': ["希望明天天气好。", "xīwàng míngtiān tiānqì hǎo", "I hope the weather is good tomorrow."],
  '带': ["出门记得带伞。", "chūmén jìde dài sǎn", "Remember to take an umbrella when you go out."],
  '帮': ["你能帮我一下吗?", "nǐ néng bāng wǒ yíxià ma", "Could you help me for a moment?"],
  '幼崽': ["母狮在照看幼崽。", "mǔshī zài zhàokàn yòuzǎi", "The lioness is looking after her cubs."],
  '床': ["床边放着一盏灯。", "chuáng biān fàng zhe yì zhǎn dēng", "There is a lamp beside the bed."],
  '建立': ["两国建立了新关系。", "liǎng guó jiànlì le xīn guānxì", "The two countries established a new relationship."],
  '开': ["请开一下窗户。", "qǐng kāi yíxià chuānghu", "Please open the window."],
  '开始': ["会议九点开始。", "huìyì jiǔ diǎn kāishǐ", "The meeting starts at nine."],
  '影响': ["天气影响了航班。", "tiānqì yǐngxiǎng le hángbān", "The weather affected the flights."],
  '微波炉': ["用微波炉热一下饭。", "yòng wēibōlú rè yíxià fàn", "Heat the rice up in the microwave."],
  '忘': ["别忘了带钥匙。", "bié wàng le dài yàoshi", "Do not forget to take your keys."],
  '想': ["我想再喝一杯茶。", "wǒ xiǎng zài hē yì bēi chá", "I would like another cup of tea."],
  '房东': ["房东下周来收租金。", "fángdōng xià zhōu lái shōu zūjīn", "The landlord is coming to collect the rent next week."],
  '房子': ["这套房子有三个房间。", "zhè tào fángzi yǒu sān gè fángjiān", "This house has three rooms."],
  '房间': ["这个房间光线很好。", "zhège fángjiān guāngxiàn hěn hǎo", "This room has good light."],
  '打扫': ["周末要打扫房间。", "zhōumò yào dǎsǎo fángjiān", "The room needs cleaning at the weekend."],
  '找': ["我在找我的手机。", "wǒ zài zhǎo wǒ de shǒujī", "I am looking for my phone."],
  '承认': ["我承认是我的错。", "wǒ chéngrèn shì wǒ de cuò", "I admit it was my fault."],
  '抽屉': ["剪刀在抽屉里。", "jiǎndāo zài chōuti lǐ", "The scissors are in the drawer."],
  '拒绝': ["邀请被拒绝了。", "yāoqǐng bèi jùjué le", "The invitation was declined."],
  '拿': ["帮我拿一下包。", "bāng wǒ ná yíxià bāo", "Hold the bag for me a moment."],
  '换': ["我想换个大点的。", "wǒ xiǎng huàn gè dà diǎn de", "I would like to change it for a bigger one."],
  '接受': ["我接受这个安排。", "wǒ jiēshòu zhège ānpái", "I accept this arrangement."],
  '提高': ["我想提高中文水平。", "wǒ xiǎng tígāo Zhōngwén shuǐpíng", "I want to improve my Chinese."],
  '插座': ["这里没有插座。", "zhèlǐ méiyǒu chāzuò", "There is no power socket here."],
  '搬家': ["我们下个月搬家。", "wǒmen xià gè yuè bānjiā", "We are moving house next month."],
  '支持': ["大家都支持这个想法。", "dàjiā dōu zhīchí zhège xiǎngfǎ", "Everyone supports this idea."],
  '改变': ["计划改变了。", "jìhuà gǎibiàn le", "The plan has changed."],
  '放': ["把书放在桌上。", "bǎ shū fàng zài zhuō shàng", "Put the book on the desk."],
  '放弃': ["别这么快就放弃。", "bié zhème kuài jiù fàngqì", "Do not give up so quickly."],
  '教': ["是谁教你的?", "shì shéi jiāo nǐ de", "Who taught you?"],
  '整理': ["请把桌子整理一下。", "qǐng bǎ zhuōzi zhěnglǐ yíxià", "Please tidy the table up."],
  '斑马': ["斑马身上有黑白条纹。", "bānmǎ shēnshàng yǒu hēibái tiáowén", "Zebras have black and white stripes."],
  '新鲜': ["早市的菜最新鲜。", "zǎoshì de cài zuì xīnxiān", "Vegetables at the morning market are freshest."],
  '早饭': ["我每天都吃早饭。", "wǒ měitiān dōu chī zǎofàn", "I eat breakfast every day."],
  '昆虫': ["这本书讲各种昆虫。", "zhè běn shū jiǎng gèzhǒng kūnchóng", "This book is about various insects."],
  '是': ["这是我的位子。", "zhè shì wǒ de wèizi", "This is my seat."],
  '晚饭': ["晚饭已经准备好了。", "wǎnfàn yǐjīng zhǔnbèi hǎo le", "Dinner is already ready."],
  '暖气': ["冬天这里有暖气。", "dōngtiān zhèlǐ yǒu nuǎnqì", "There is heating here in winter."],
  '有': ["桌上有两本书。", "zhuō shàng yǒu liǎng běn shū", "There are two books on the desk."],
  '来': ["客人快来了。", "kèrén kuài lái le", "The guests will be here soon."],
  '杯子': ["杯子里的水凉了。", "bēizi lǐ de shuǐ liáng le", "The water in the cup has gone cold."],
  '枕头': ["这个枕头有点儿高。", "zhège zhěntou yǒudiǎnr gāo", "This pillow is a bit too high."],
  '桃子': ["桃子熟了就很软。", "táozi shú le jiù hěn ruǎn", "Peaches go soft once ripe."],
  '桌子': ["桌子上有一杯茶。", "zhuōzi shàng yǒu yì bēi chá", "There is a cup of tea on the table."],
  '椅子': ["这把椅子坐着很舒服。", "zhè bǎ yǐzi zuò zhe hěn shūfu", "This chair is comfortable to sit in."],
  '楼上': ["楼上还有两个房间。", "lóushàng hái yǒu liǎng gè fángjiān", "There are two more rooms upstairs."],
  '楼下': ["楼下开了家新店。", "lóuxià kāi le jiā xīn diàn", "A new shop opened downstairs."],
  '楼梯': ["楼梯很窄,小心点。", "lóutī hěn zhǎi, xiǎoxīn diǎn", "The stairs are narrow, be careful."],
  '橙子': ["我剥了一个橙子。", "wǒ bāo le yí gè chéngzi", "I peeled an orange."],
  '比较': ["我们比较了两个方案。", "wǒmen bǐjiào le liǎng gè fāng'àn", "We compared the two proposals."],
  '毛': ["这只猫的毛很软。", "zhè zhī māo de máo hěn ruǎn", "This cat's fur is very soft."],
  '毛巾': ["毛巾挂在门后。", "máojīn guà zài mén hòu", "The towel is hanging behind the door."],
  '毯子': ["沙发上放着一条毯子。", "shāfā shàng fàng zhe yì tiáo tǎnzi", "There is a blanket on the sofa."],
  '水': ["请给我一杯水。", "qǐng gěi wǒ yì bēi shuǐ", "Please give me a glass of water."],
  '水果': ["饭后吃点水果吧。", "fàn hòu chī diǎn shuǐguǒ ba", "Have some fruit after the meal."],
  '水龙头': ["水龙头没关紧。", "shuǐlóngtóu méi guān jǐn", "The faucet is not turned off tightly."],
  '汤': ["先喝一碗汤。", "xiān hē yì wǎn tāng", "Have a bowl of soup first."],
  '沙发': ["猫睡在沙发上。", "māo shuì zài shāfā shàng", "The cat is sleeping on the sofa."],
  '洋葱': ["切洋葱的时候会流泪。", "qiē yángcōng de shíhou huì liúlèi", "Cutting onions makes your eyes water."],
  '洗': ["手洗过了吗?", "shǒu xǐ guò le ma", "Have you washed your hands?"],
  '洗衣机': ["洗衣机还在转。", "xǐyījī hái zài zhuàn", "The washing machine is still running."],
  '洞': ["兔子躲进洞里了。", "tùzi duǒ jìn dòng lǐ le", "The rabbit hid in its burrow."],
  '浴室': ["浴室里没有窗户。", "yùshì lǐ méiyǒu chuānghu", "There is no window in the bathroom."],
  '海豚': ["海豚很喜欢跟人玩。", "hǎitún hěn xǐhuan gēn rén wán", "Dolphins love playing with people."],
  '海鲜': ["海边的海鲜很便宜。", "hǎibiān de hǎixiān hěn piányi", "Seafood is cheap by the sea."],
  '温馨': ["这个家很温馨。", "zhège jiā hěn wēnxīn", "This home feels very cozy."],
  '渴': ["天热容易口渴。", "tiān rè róngyì kǒukě", "You get thirsty easily in hot weather."],
  '漏水': ["厨房的管子在漏水。", "chúfáng de guǎnzi zài lòushuǐ", "The kitchen pipe is leaking."],
  '灭绝': ["很多动物已经灭绝了。", "hěn duō dòngwù yǐjīng mièjué le", "Many animals have already gone extinct."],
  '灯': ["睡觉前把灯关上。", "shuìjiào qián bǎ dēng guān shàng", "Turn the light off before going to sleep."],
  '炒': ["我炒了一盘青菜。", "wǒ chǎo le yì pán qīngcài", "I stir-fried a plate of greens."],
  '点心': ["下午茶配了几样点心。", "xiàwǔchá pèi le jǐ yàng diǎnxin", "The afternoon tea came with a few snacks."],
  '烤': ["烤了一只鸡当晚饭。", "kǎo le yì zhī jī dāng wǎnfàn", "Roasted a chicken for dinner."],
  '烤箱': ["面包在烤箱里。", "miànbāo zài kǎoxiāng lǐ", "The bread is in the oven."],
  '煎': ["早上煎了两个鸡蛋。", "zǎoshang jiān le liǎng gè jīdàn", "Fried two eggs this morning."],
  '煮': ["鸡蛋煮了十分钟。", "jīdàn zhǔ le shí fēnzhōng", "The eggs boiled for ten minutes."],
  '熊': ["冬天熊要睡很久。", "dōngtiān xióng yào shuì hěn jiǔ", "Bears sleep for a long time in winter."],
  '熊猫': ["熊猫只吃竹子。", "xióngmāo zhǐ chī zhúzi", "Pandas eat only bamboo."],
  '爪子': ["猫的爪子很锋利。", "māo de zhuǎzi hěn fēnglì", "A cat's claws are very sharp."],
  '爬': ["孩子爬上了树。", "háizi pá shàng le shù", "The child climbed the tree."],
  '牙刷': ["我的牙刷该换了。", "wǒ de yáshuā gāi huàn le", "My toothbrush needs replacing."],
  '牛': ["牛在地里吃草。", "niú zài dì lǐ chī cǎo", "The cow is grazing in the field."],
  '牛奶': ["牛奶放冰箱里了。", "niúnǎi fàng bīngxiāng lǐ le", "The milk has been put in the fridge."],
  '牛肉': ["牛肉比鸡肉贵一些。", "niúròu bǐ jīròu guì yìxiē", "Beef is a bit dearer than chicken."],
  '物业': ["有问题可以找物业。", "yǒu wèntí kěyǐ zhǎo wùyè", "You can take any problem to property management."],
  '物种': ["这个物种很少见。", "zhège wùzhǒng hěn shǎojiàn", "This species is rarely seen."],
  '牲畜': ["农场里养着很多牲畜。", "nóngchǎng lǐ yǎng zhe hěn duō shēngchù", "The farm keeps a lot of livestock."],
  '狐狸': ["狐狸很聪明。", "húli hěn cōngming", "Foxes are very clever."],
  '狗': ["门口有一只狗。", "ménkǒu yǒu yì zhī gǒu", "There is a dog at the door."],
  '狮子': ["狮子的叫声很大。", "shīzi de jiàoshēng hěn dà", "A lion's roar is very loud."],
  '狼': ["狼在夜里出来找食。", "láng zài yèlǐ chūlái zhǎo shí", "Wolves come out at night to find food."],
  '猎人': ["猎人带着狗进山。", "lièrén dài zhe gǒu jìn shān", "The hunter went into the hills with dogs."],
  '猎物': ["狼在等待猎物。", "láng zài děngdài lièwù", "The wolf is waiting for prey."],
  '猪': ["农场里养了几头猪。", "nóngchǎng lǐ yǎng le jǐ tóu zhū", "The farm keeps a few pigs."],
  '猪肉': ["饺子馅是猪肉的。", "jiǎozi xiàn shì zhūròu de", "The dumpling filling is pork."],
  '猫': ["猫喜欢睡在窗台上。", "māo xǐhuan shuì zài chuāngtái shàng", "Cats like sleeping on the windowsill."],
  '猫咪': ["那只猫咪很亲人。", "nà zhī māomī hěn qīnrén", "That kitty is very friendly with people."],
  '猫头鹰': ["猫头鹰晚上才活动。", "māotóuyīng wǎnshang cái huódòng", "Owls are only active at night."],
  '猴子': ["猴子会爬树。", "hóuzi huì pá shù", "Monkeys can climb trees."],
  '玉米': ["夏天的玉米特别甜。", "xiàtiān de yùmǐ tèbié tián", "Summer corn is especially sweet."],
  '甜': ["这杯茶不太甜。", "zhè bēi chá bú tài tián", "This cup of tea is not very sweet."],
  '用': ["这个词很少用。", "zhège cí hěn shǎo yòng", "This word is rarely used."],
  '电器': ["家里的电器都很旧了。", "jiā lǐ de diànqì dōu hěn jiù le", "The appliances at home are all old."],
  '电视': ["晚饭后我们看电视。", "wǎnfàn hòu wǒmen kàn diànshì", "We watch television after dinner."],
  '皮毛': ["这种动物的皮毛很厚。", "zhè zhǒng dòngwù de pímáo hěn hòu", "This animal's coat is very thick."],
  '盐': ["汤里的盐放多了。", "tāng lǐ de yán fàng duō le", "Too much salt went into the soup."],
  '盘子': ["盘子洗好放在这里。", "pánzi xǐ hǎo fàng zài zhèlǐ", "The washed plates go here."],
  '看': ["让我看一下地图。", "ràng wǒ kàn yíxià dìtú", "Let me have a look at the map."],
  '睡': ["昨晚我睡得很好。", "zuówǎn wǒ shuì de hěn hǎo", "I slept well last night."],
  '知道': ["这件事我不知道。", "zhè jiàn shì wǒ bù zhīdào", "I do not know about this."],
  '碗': ["请再给我一个碗。", "qǐng zài gěi wǒ yí gè wǎn", "Please give me another bowl."],
  '租金': ["这里的租金太高了。", "zhèlǐ de zūjīn tài gāo le", "The rent here is too high."],
  '空调': ["太热了,开空调吧。", "tài rè le, kāi kōngtiáo ba", "It is too hot, let us put the air conditioning on."],
  '穿': ["今天穿得太少了。", "jīntiān chuān de tài shǎo le", "I am not dressed warmly enough today."],
  '窗帘': ["早上拉开窗帘。", "zǎoshang lā kāi chuānglián", "Open the curtains in the morning."],
  '窗户': ["窗户开着,风很大。", "chuānghu kāi zhe, fēng hěn dà", "The window is open and it is windy."],
  '站': ["别站在门口。", "bié zhàn zài ménkǒu", "Do not stand in the doorway."],
  '等': ["请等我五分钟。", "qǐng děng wǒ wǔ fēnzhōng", "Please wait five minutes for me."],
  '筷子': ["用筷子吃面更方便。", "yòng kuàizi chī miàn gèng fāngbiàn", "It is easier to eat noodles with chopsticks."],
  '米': ["家里的米快吃完了。", "jiā lǐ de mǐ kuài chī wán le", "We are almost out of rice at home."],
  '米饭': ["米饭还没煮好。", "mǐfàn hái méi zhǔ hǎo", "The rice is not cooked yet."],
  '粥': ["生病时喝点粥比较好。", "shēngbìng shí hē diǎn zhōu bǐjiào hǎo", "Porridge is better when you are ill."],
  '糖': ["我的咖啡不放糖。", "wǒ de kāfēi bú fàng táng", "I do not take sugar in my coffee."],
  '素食': ["我最近改吃素食。", "wǒ zuìjìn gǎi chī sùshí", "I have switched to vegetarian food lately."],
  '结束': ["课已经结束了。", "kè yǐjīng jiéshù le", "The class has already ended."],
  '给': ["请给我一张纸。", "qǐng gěi wǒ yì zhāng zhǐ", "Please give me a sheet of paper."],
  '继续': ["休息一下再继续。", "xiūxi yíxià zài jìxù", "Take a break and then carry on."],
  '羊': ["山上有一群羊。", "shān shàng yǒu yì qún yáng", "There is a flock of sheep on the hill."],
  '群': ["一群鸟飞过天空。", "yì qún niǎo fēi guò tiānkōng", "A flock of birds flew across the sky."],
  '羽毛': ["地上掉了一根羽毛。", "dì shàng diào le yì gēn yǔmáo", "A feather fell on the ground."],
  '翅膀': ["这只鸟的翅膀受伤了。", "zhè zhī niǎo de chìbǎng shòushāng le", "This bird's wing is injured."],
  '老虎': ["老虎是很危险的动物。", "lǎohǔ shì hěn wēixiǎn de dòngwù", "Tigers are dangerous animals."],
  '老鼠': ["厨房里有老鼠。", "chúfáng lǐ yǒu lǎoshǔ", "There are mice in the kitchen."],
  '肉': ["这个菜里没有肉。", "zhège cài lǐ méiyǒu ròu", "There is no meat in this dish."],
  '肥皂': ["洗手要用肥皂。", "xǐ shǒu yào yòng féizào", "Use soap when you wash your hands."],
  '胡萝卜': ["兔子最爱吃胡萝卜。", "tùzi zuì ài chī húluóbo", "Rabbits love carrots best."],
  '舒适': ["这个房间很舒适。", "zhège fángjiān hěn shūshì", "This room is very comfortable."],
  '芒果': ["我对芒果过敏。", "wǒ duì mángguǒ guòmǐn", "I am allergic to mango."],
  '花园': ["房子后面有个小花园。", "fángzi hòumiàn yǒu gè xiǎo huāyuán", "There is a small garden behind the house."],
  '苍蝇': ["一只苍蝇飞进屋里。", "yì zhī cāngying fēi jìn wū lǐ", "A fly flew into the room."],
  '苦': ["这药很苦。", "zhè yào hěn kǔ", "This medicine is very bitter."],
  '苹果': ["苹果比香蕉便宜。", "píngguǒ bǐ xiāngjiāo piányi", "Apples are cheaper than bananas."],
  '茶': ["我喜欢喝热茶。", "wǒ xǐhuan hē rè chá", "I like drinking hot tea."],
  '草莓': ["这些草莓又大又甜。", "zhèxiē cǎoméi yòu dà yòu tián", "These strawberries are big and sweet."],
  '菜': ["今天的菜有点咸。", "jīntiān de cài yǒudiǎn xián", "Today's dish is a little salty."],
  '菠萝': ["菠萝要削皮才能吃。", "bōluó yào xiāo pí cái néng chī", "Pineapple has to be peeled before eating."],
  '营养': ["早饭要有营养。", "zǎofàn yào yǒu yíngyǎng", "Breakfast should be nutritious."],
  '葡萄': ["这串葡萄有点酸。", "zhè chuàn pútáo yǒudiǎn suān", "This bunch of grapes is a little sour."],
  '蒸': ["这鱼是蒸出来的。", "zhè yú shì zhēng chūlái de", "This fish was steamed."],
  '蔬菜': ["多吃蔬菜对身体好。", "duō chī shūcài duì shēntǐ hǎo", "Eating more vegetables is good for you."],
  '虫子': ["叶子上有只虫子。", "yèzi shàng yǒu zhī chóngzi", "There is a bug on the leaf."],
  '虾': ["这盘虾很新鲜。", "zhè pán xiā hěn xīnxiān", "This plate of shrimp is very fresh."],
  '蚂蚁': ["一队蚂蚁在搬东西。", "yí duì mǎyǐ zài bān dōngxi", "A line of ants is carrying things."],
  '蚊子': ["夏天的蚊子特别多。", "xiàtiān de wénzi tèbié duō", "There are especially many mosquitoes in summer."],
  '蛇': ["草里有一条蛇。", "cǎo lǐ yǒu yì tiáo shé", "There is a snake in the grass."],
  '蜘蛛': ["角落里有个蜘蛛网。", "jiǎoluò lǐ yǒu gè zhīzhūwǎng", "There is a spider web in the corner."],
  '蜜蜂': ["花园里有很多蜜蜂。", "huāyuán lǐ yǒu hěn duō mìfēng", "There are many bees in the garden."],
  '蝴蝶': ["一只蝴蝶飞过来了。", "yì zhī húdié fēi guòlái le", "A butterfly flew over."],
  '螃蟹': ["螃蟹横着走路。", "pángxiè héng zhe zǒulù", "Crabs walk sideways."],
  '衣柜': ["衣服都挂在衣柜里。", "yīfu dōu guà zài yīguì lǐ", "The clothes are all hanging in the wardrobe."],
  '被子': ["天冷了,加一床被子。", "tiān lěng le, jiā yì chuáng bèizi", "It is getting cold, add another quilt."],
  '装修': ["房子正在装修。", "fángzi zhèngzài zhuāngxiū", "The house is being renovated."],
  '西瓜': ["夏天最适合吃西瓜。", "xiàtiān zuì shìhé chī xīguā", "Summer is the best time for watermelon."],
  '西红柿': ["汤里放两个西红柿。", "tāng lǐ fàng liǎng gè xīhóngshì", "Put two tomatoes in the soup."],
  '要': ["这件事要花很多时间。", "zhè jiàn shì yào huā hěn duō shíjiān", "This is going to take a lot of time."],
  '角落': ["书放在房间的角落里。", "shū fàng zài fángjiān de jiǎoluò lǐ", "The books are in the corner of the room."],
  '解决': ["问题终于解决了。", "wèntí zhōngyú jiějué le", "The problem is finally solved."],
  '记得': ["我不记得那家店的名字。", "wǒ bú jìde nà jiā diàn de míngzi", "I do not remember the name of that shop."],
  '试': ["这件衣服我想试试。", "zhè jiàn yīfu wǒ xiǎng shìshi", "I would like to try this on."],
  '说': ["请说慢一点。", "qǐng shuō màn yìdiǎn", "Please speak a bit more slowly."],
  '读': ["这本书我读了两遍。", "zhè běn shū wǒ dú le liǎng biàn", "I have read this book twice."],
  '调料': ["别放太多调料。", "bié fàng tài duō tiáoliào", "Do not add too much seasoning."],
  '豆腐': ["麻婆豆腐是川菜。", "mápó dòufu shì chuāncài", "Mapo tofu is a Sichuan dish."],
  '走': ["我们走路去吧。", "wǒmen zǒulù qù ba", "Let us walk there."],
  '跑': ["别在楼道里跑。", "bié zài lóudào lǐ pǎo", "Do not run in the hallway."],
  '车位': ["楼下的车位都满了。", "lóuxià de chēwèi dōu mǎn le", "The parking spaces downstairs are all full."],
  '车库': ["车库里停着一辆车。", "chēkù lǐ tíng zhe yí liàng chē", "There is a car parked in the garage."],
  '辣': ["这个菜太辣了。", "zhège cài tài là le", "This dish is too spicy."],
  '辣椒': ["这种辣椒特别辣。", "zhè zhǒng làjiāo tèbié là", "This kind of chili is especially hot."],
  '迁徙': ["候鸟每年都要迁徙。", "hòuniǎo měinián dōu yào qiānxǐ", "Migratory birds migrate every year."],
  '进': ["请进,门开着。", "qǐng jìn, mén kāi zhe", "Come in, the door is open."],
  '送': ["这本书是朋友送的。", "zhè běn shū shì péngyou sòng de", "This book was a gift from a friend."],
  '选': ["这两个你选哪个?", "zhè liǎng gè nǐ xuǎn nǎge", "Which of these two do you choose?"],
  '通风': ["这个房间通风很好。", "zhège fángjiān tōngfēng hěn hǎo", "This room is well ventilated."],
  '避免': ["这样可以避免误会。", "zhèyàng kěyǐ bìmiǎn wùhuì", "This way you avoid misunderstandings."],
  '酱油': ["炒菜时加点酱油。", "chǎocài shí jiā diǎn jiàngyóu", "Add a little soy sauce when stir-frying."],
  '酸': ["柠檬又酸又香。", "níngméng yòu suān yòu xiāng", "Lemons are sour and fragrant."],
  '酸奶': ["我早上喝一杯酸奶。", "wǒ zǎoshang hē yì bēi suānnǎi", "I have a cup of yogurt in the morning."],
  '醋': ["饺子要蘸醋吃。", "jiǎozi yào zhàn cù chī", "Dumplings are eaten dipped in vinegar."],
  '野生': ["这里有很多野生动物。", "zhèlǐ yǒu hěn duō yěshēng dòngwù", "There is a lot of wildlife here."],
  '钥匙': ["我的钥匙找不到了。", "wǒ de yàoshi zhǎo bu dào le", "I cannot find my keys."],
  '镜子': ["镜子上有一层水汽。", "jìngzi shàng yǒu yì céng shuǐqì", "There is a film of steam on the mirror."],
  '长颈鹿': ["长颈鹿能吃到高处的叶子。", "chángjǐnglù néng chī dào gāochù de yèzi", "Giraffes can reach the leaves up high."],
  '门': ["出去的时候请关门。", "chūqù de shíhou qǐng guān mén", "Please close the door when you go out."],
  '门铃': ["有人按门铃。", "yǒu rén àn ménlíng", "Someone is ringing the doorbell."],
  '问': ["我想问一个问题。", "wǒ xiǎng wèn yí gè wèntí", "I would like to ask a question."],
  '阳台': ["阳台上晒着衣服。", "yángtái shàng shài zhe yīfu", "Clothes are drying on the balcony."],
  '需要': ["这里需要一把椅子。", "zhèlǐ xūyào yì bǎ yǐzi", "A chair is needed here."],
  '青蛙': ["雨后能听见青蛙叫。", "yǔ hòu néng tīngjiàn qīngwā jiào", "You can hear frogs after the rain."],
  '面包': ["早上吃了两片面包。", "zǎoshang chī le liǎng piàn miànbāo", "I ate two slices of bread this morning."],
  '面条': ["中午我想吃面条。", "zhōngwǔ wǒ xiǎng chī miàntiáo", "I want noodles for lunch."],
  '飞': ["鸟飞得很高。", "niǎo fēi de hěn gāo", "The bird flies very high."],
  '食物': ["这些食物不能久放。", "zhèxiē shíwù bùnéng jiǔ fàng", "This food cannot be kept for long."],
  '食谱': ["这本食谱很实用。", "zhè běn shípǔ hěn shíyòng", "This recipe book is very practical."],
  '饱': ["我已经吃饱了。", "wǒ yǐjīng chī bǎo le", "I am already full."],
  '饺子': ["过年时全家包饺子。", "guònián shí quánjiā bāo jiǎozi", "At New Year the whole family makes dumplings."],
  '饼干': ["孩子把饼干都吃完了。", "háizi bǎ bǐnggān dōu chī wán le", "The child ate all the biscuits."],
  '饿': ["走了一天很饿。", "zǒu le yì tiān hěn è", "Walked all day and I am hungry."],
  '香蕉': ["香蕉已经太熟了。", "xiāngjiāo yǐjīng tài shú le", "The bananas are already too ripe."],
  '马': ["草原上有一群马。", "cǎoyuán shàng yǒu yì qún mǎ", "There is a herd of horses on the grassland."],
  '驯养': ["狗是最早被驯养的。", "gǒu shì zuì zǎo bèi xùnyǎng de", "Dogs were the first to be domesticated."],
  '骆驼': ["骆驼能走很远的沙漠。", "luòtuo néng zǒu hěn yuǎn de shāmò", "Camels can cross long stretches of desert."],
  '鱼': ["这条鱼很新鲜。", "zhè tiáo yú hěn xīnxiān", "This fish is very fresh."],
  '鲨鱼': ["这片海里有鲨鱼。", "zhè piàn hǎi lǐ yǒu shāyú", "There are sharks in this stretch of sea."],
  '鲸鱼': ["鲸鱼是最大的动物。", "jīngyú shì zuì dà de dòngwù", "The whale is the largest animal."],
  '鸟': ["树上有很多鸟。", "shù shàng yǒu hěn duō niǎo", "There are many birds in the tree."],
  '鸡': ["院子里养着几只鸡。", "yuànzi lǐ yǎng zhe jǐ zhī jī", "A few chickens are kept in the yard."],
  '鸡肉': ["这块鸡肉还没熟。", "zhè kuài jīròu hái méi shú", "This piece of chicken is not cooked yet."],
  '鸡蛋': ["冰箱里还有三个鸡蛋。", "bīngxiāng lǐ háiyǒu sān gè jīdàn", "There are still three eggs in the fridge."],
  '鸭': ["河里游着两只鸭。", "hé lǐ yóu zhe liǎng zhī yā", "Two ducks are swimming in the river."],
  '鸽子': ["广场上有很多鸽子。", "guǎngchǎng shàng yǒu hěn duō gēzi", "There are many pigeons in the square."],
  '鹅': ["鹅比鸭子大。", "é bǐ yāzi dà", "Geese are bigger than ducks."],
  '鹿': ["森林里跑过一只鹿。", "sēnlín lǐ pǎo guò yì zhī lù", "A deer ran through the forest."],
  '黄油': ["面包上抹点黄油。", "miànbāo shàng mǒ diǎn huángyóu", "Spread a little butter on the bread."],
  '龙': ["中国人喜欢龙。", "Zhōngguórén xǐhuan lóng", "Chinese people are fond of dragons."]
};

/** The example for a word, or null. */
export function sentenceFor(zh) {
  return SENTENCES[zh] ?? null;
}
