// Word decks. Simplified characters, Mandarin, with US English glosses.
//
// The `zh` string is the progress key, so it is a stable identifier before it
// is a display string: never rewrite one that has shipped, or you silently
// orphan every card anyone has built on it. Add a new entry and retire the old
// one instead. Moving a word between stages is safe — the key does not change,
// and the stage is only where the word sits.
//
// Pinyin carries tone marks rather than tone numbers. It is shown to the
// learner, and `ni3 hao3` is not something anybody reads aloud. Tones are
// checked against the Unicode Han Database by tools/check-vocab.mjs, one
// syllable per character; a wrong tone is the error nobody catches by eye and
// the one that teaches somebody to say a word wrong for years.
//
// A word that appears in two decks — 鱼 is both food and an animal — is one
// card, met in two places. Both entries must then gloss it identically, or the
// same card teaches two different answers depending on where you met it. The
// checker enforces this.
//
// Structure mirrors Vocabulario: 25 decks, three stages each, at half its
// depth. Seven decks are deliberately smaller, and for the same reasons its
// are — Numbers Basics *is* 0–20, and Questions & Connectors is a closed class
// throughout. Padding those to a round number would mean inventing filler.
//
// NOT YET REVIEWED BY A NATIVE SPEAKER. The tones are machine-checked against
// Unihan and the glosses were written to be the plainest common equivalent,
// but register and naturalness need a human read.

export const STAGE_NAMES = ['Basics', 'Everyday', 'Fluent'];
export const STAGE_COUNT = STAGE_NAMES.length;
export const ALL_DECK_ID = 'quanbu';

export const DECKS = [
  {
    id: 'shiwu',
    name: 'Food',
    emoji: '🍜',
    stages: [
      [
        { zh: '水', py: 'shuǐ', en: 'water' },
        { zh: '茶', py: 'chá', en: 'tea' },
        { zh: '米饭', py: 'mǐfàn', en: 'cooked rice' },
        { zh: '面包', py: 'miànbāo', en: 'bread' },
        { zh: '鸡蛋', py: 'jīdàn', en: 'egg' },
        { zh: '肉', py: 'ròu', en: 'meat' },
        { zh: '鱼', py: 'yú', en: 'fish' },
        { zh: '苹果', py: 'píngguǒ', en: 'apple' },
        { zh: '香蕉', py: 'xiāngjiāo', en: 'banana' },
        { zh: '水果', py: 'shuǐguǒ', en: 'fruit' },
        { zh: '蔬菜', py: 'shūcài', en: 'vegetable' },
        { zh: '食物', py: 'shíwù', en: 'food' },
        { zh: '吃', py: 'chī', en: 'to eat' },
        { zh: '喝', py: 'hē', en: 'to drink' },
        { zh: '牛奶', py: 'niúnǎi', en: 'milk' },
        { zh: '咖啡', py: 'kāfēi', en: 'coffee' },
        { zh: '糖', py: 'táng', en: 'sugar' },
        { zh: '盐', py: 'yán', en: 'salt' },
        { zh: '汤', py: 'tāng', en: 'soup' },
        { zh: '面条', py: 'miàntiáo', en: 'noodles' },
        { zh: '饺子', py: 'jiǎozi', en: 'dumpling' },
        { zh: '包子', py: 'bāozi', en: 'steamed bun' },
        { zh: '好吃', py: 'hǎochī', en: 'tasty' },
        { zh: '菜', py: 'cài', en: 'dish of food' },
        { zh: '早饭', py: 'zǎofàn', en: 'breakfast' }
      ],
      [
        { zh: '午饭', py: 'wǔfàn', en: 'lunch' },
        { zh: '晚饭', py: 'wǎnfàn', en: 'dinner' },
        { zh: '草莓', py: 'cǎoméi', en: 'strawberry' },
        { zh: '橙子', py: 'chéngzi', en: 'orange' },
        { zh: '西瓜', py: 'xīguā', en: 'watermelon' },
        { zh: '葡萄', py: 'pútáo', en: 'grape' },
        { zh: '桃子', py: 'táozi', en: 'peach' },
        { zh: '芒果', py: 'mángguǒ', en: 'mango' },
        { zh: '菠萝', py: 'bōluó', en: 'pineapple' },
        { zh: '西红柿', py: 'xīhóngshì', en: 'tomato' },
        { zh: '土豆', py: 'tǔdòu', en: 'potato' },
        { zh: '胡萝卜', py: 'húluóbo', en: 'carrot' },
        { zh: '洋葱', py: 'yángcōng', en: 'onion' },
        { zh: '大蒜', py: 'dàsuàn', en: 'garlic' },
        { zh: '玉米', py: 'yùmǐ', en: 'corn' },
        { zh: '黄油', py: 'huángyóu', en: 'butter' },
        { zh: '酸奶', py: 'suānnǎi', en: 'yogurt' },
        { zh: '鸡肉', py: 'jīròu', en: 'chicken meat' },
        { zh: '牛肉', py: 'niúròu', en: 'beef' },
        { zh: '猪肉', py: 'zhūròu', en: 'pork' },
        { zh: '米', py: 'mǐ', en: 'uncooked rice' },
        { zh: '粥', py: 'zhōu', en: 'porridge' },
        { zh: '点心', py: 'diǎnxin', en: 'snack' },
        { zh: '饼干', py: 'bǐnggān', en: 'biscuit' },
        { zh: '巧克力', py: 'qiǎokèlì', en: 'chocolate' }
      ],
      [
        { zh: '辣', py: 'là', en: 'spicy' },
        { zh: '甜', py: 'tián', en: 'sweet' },
        { zh: '酸', py: 'suān', en: 'sour' },
        { zh: '苦', py: 'kǔ', en: 'bitter' },
        { zh: '咸', py: 'xián', en: 'salty' },
        { zh: '味道', py: 'wèidào', en: 'flavor' },
        { zh: '新鲜', py: 'xīnxiān', en: 'fresh' },
        { zh: '煮', py: 'zhǔ', en: 'to boil' },
        { zh: '炒', py: 'chǎo', en: 'to stir-fry' },
        { zh: '蒸', py: 'zhēng', en: 'to steam' },
        { zh: '烤', py: 'kǎo', en: 'to roast' },
        { zh: '煎', py: 'jiān', en: 'to pan-fry' },
        { zh: '食谱', py: 'shípǔ', en: 'recipe' },
        { zh: '调料', py: 'tiáoliào', en: 'seasoning' },
        { zh: '酱油', py: 'jiàngyóu', en: 'soy sauce' },
        { zh: '醋', py: 'cù', en: 'vinegar' },
        { zh: '辣椒', py: 'làjiāo', en: 'chili pepper' },
        { zh: '豆腐', py: 'dòufu', en: 'tofu' },
        { zh: '海鲜', py: 'hǎixiān', en: 'seafood' },
        { zh: '素食', py: 'sùshí', en: 'vegetarian food' },
        { zh: '营养', py: 'yíngyǎng', en: 'nutrition' },
        { zh: '饱', py: 'bǎo', en: 'full from eating' },
        { zh: '饿', py: 'è', en: 'hungry' },
        { zh: '渴', py: 'kě', en: 'thirsty' },
        { zh: '尝', py: 'cháng', en: 'to taste' }
      ]
    ]
  },
  {
    id: 'dongwu',
    name: 'Animals',
    emoji: '🐼',
    stages: [
      [
        { zh: '狗', py: 'gǒu', en: 'dog' },
        { zh: '猫', py: 'māo', en: 'cat' },
        { zh: '鸟', py: 'niǎo', en: 'bird' },
        { zh: '马', py: 'mǎ', en: 'horse' },
        { zh: '牛', py: 'niú', en: 'cow' },
        { zh: '猪', py: 'zhū', en: 'pig' },
        { zh: '羊', py: 'yáng', en: 'sheep' },
        { zh: '鸡', py: 'jī', en: 'chicken' },
        { zh: '鸭', py: 'yā', en: 'duck' },
        { zh: '鱼', py: 'yú', en: 'fish' },
        { zh: '动物', py: 'dòngwù', en: 'animal' },
        { zh: '熊猫', py: 'xióngmāo', en: 'panda' },
        { zh: '老虎', py: 'lǎohǔ', en: 'tiger' },
        { zh: '狮子', py: 'shīzi', en: 'lion' },
        { zh: '熊', py: 'xióng', en: 'bear' },
        { zh: '猴子', py: 'hóuzi', en: 'monkey' },
        { zh: '大象', py: 'dàxiàng', en: 'elephant' },
        { zh: '兔子', py: 'tùzi', en: 'rabbit' },
        { zh: '老鼠', py: 'lǎoshǔ', en: 'mouse' },
        { zh: '蛇', py: 'shé', en: 'snake' },
        { zh: '龙', py: 'lóng', en: 'dragon' },
        { zh: '宠物', py: 'chǒngwù', en: 'pet' },
        { zh: '尾巴', py: 'wěiba', en: 'tail' },
        { zh: '虫子', py: 'chóngzi', en: 'bug' },
        { zh: '鹅', py: 'é', en: 'goose' }
      ],
      [
        { zh: '蜜蜂', py: 'mìfēng', en: 'bee' },
        { zh: '蝴蝶', py: 'húdié', en: 'butterfly' },
        { zh: '青蛙', py: 'qīngwā', en: 'frog' },
        { zh: '乌龟', py: 'wūguī', en: 'turtle' },
        { zh: '狼', py: 'láng', en: 'wolf' },
        { zh: '狐狸', py: 'húli', en: 'fox' },
        { zh: '鹿', py: 'lù', en: 'deer' },
        { zh: '鲸鱼', py: 'jīngyú', en: 'whale' },
        { zh: '鲨鱼', py: 'shāyú', en: 'shark' },
        { zh: '螃蟹', py: 'pángxiè', en: 'crab' },
        { zh: '虾', py: 'xiā', en: 'shrimp' },
        { zh: '蚂蚁', py: 'mǎyǐ', en: 'ant' },
        { zh: '蜘蛛', py: 'zhīzhū', en: 'spider' },
        { zh: '鸽子', py: 'gēzi', en: 'pigeon' },
        { zh: '猫头鹰', py: 'māotóuyīng', en: 'owl' },
        { zh: '翅膀', py: 'chìbǎng', en: 'wing' },
        { zh: '斑马', py: 'bānmǎ', en: 'zebra' },
        { zh: '长颈鹿', py: 'chángjǐnglù', en: 'giraffe' },
        { zh: '骆驼', py: 'luòtuo', en: 'camel' },
        { zh: '海豚', py: 'hǎitún', en: 'dolphin' },
        { zh: '蚊子', py: 'wénzi', en: 'mosquito' },
        { zh: '苍蝇', py: 'cāngying', en: 'housefly' },
        { zh: '毛', py: 'máo', en: 'fur' },
        { zh: '猫咪', py: 'māomī', en: 'kitty' },
        { zh: '小鸡', py: 'xiǎojī', en: 'chick' }
      ],
      [
        { zh: '爬', py: 'pá', en: 'to crawl' },
        { zh: '飞', py: 'fēi', en: 'to fly' },
        { zh: '咬', py: 'yǎo', en: 'to bite' },
        { zh: '喂', py: 'wèi', en: 'to feed' },
        { zh: '野生', py: 'yěshēng', en: 'wild' },
        { zh: '物种', py: 'wùzhǒng', en: 'species' },
        { zh: '灭绝', py: 'mièjué', en: 'to go extinct' },
        { zh: '爪子', py: 'zhuǎzi', en: 'claw' },
        { zh: '羽毛', py: 'yǔmáo', en: 'feather' },
        { zh: '巢', py: 'cháo', en: 'nest' },
        { zh: '洞', py: 'dòng', en: 'burrow' },
        { zh: '猎人', py: 'lièrén', en: 'hunter' },
        { zh: '猎物', py: 'lièwù', en: 'prey' },
        { zh: '昆虫', py: 'kūnchóng', en: 'insect' },
        { zh: '哺乳动物', py: 'bǔrǔdòngwù', en: 'mammal' },
        { zh: '兽医', py: 'shòuyī', en: 'veterinarian' },
        { zh: '动物园', py: 'dòngwùyuán', en: 'zoo' },
        { zh: '保护', py: 'bǎohù', en: 'to protect' },
        { zh: '驯养', py: 'xùnyǎng', en: 'to domesticate' },
        { zh: '牲畜', py: 'shēngchù', en: 'livestock' },
        { zh: '幼崽', py: 'yòuzǎi', en: 'animal young' },
        { zh: '群', py: 'qún', en: 'herd' },
        { zh: '皮毛', py: 'pímáo', en: 'pelt' },
        { zh: '孵化', py: 'fūhuà', en: 'to hatch' },
        { zh: '迁徙', py: 'qiānxǐ', en: 'to migrate' }
      ]
    ]
  },
  {
    id: 'jia',
    name: 'The Home',
    emoji: '🏠',
    stages: [
      [
        { zh: '家', py: 'jiā', en: 'home' },
        { zh: '房子', py: 'fángzi', en: 'house' },
        { zh: '门', py: 'mén', en: 'door' },
        { zh: '窗户', py: 'chuānghu', en: 'window' },
        { zh: '床', py: 'chuáng', en: 'bed' },
        { zh: '桌子', py: 'zhuōzi', en: 'table' },
        { zh: '椅子', py: 'yǐzi', en: 'chair' },
        { zh: '房间', py: 'fángjiān', en: 'room' },
        { zh: '厨房', py: 'chúfáng', en: 'kitchen' },
        { zh: '卧室', py: 'wòshì', en: 'bedroom' },
        { zh: '客厅', py: 'kètīng', en: 'living room' },
        { zh: '厕所', py: 'cèsuǒ', en: 'toilet' },
        { zh: '灯', py: 'dēng', en: 'lamp' },
        { zh: '墙', py: 'qiáng', en: 'wall' },
        { zh: '地板', py: 'dìbǎn', en: 'floor' },
        { zh: '杯子', py: 'bēizi', en: 'cup' },
        { zh: '碗', py: 'wǎn', en: 'bowl' },
        { zh: '盘子', py: 'pánzi', en: 'plate' },
        { zh: '筷子', py: 'kuàizi', en: 'chopsticks' },
        { zh: '勺子', py: 'sháozi', en: 'spoon' },
        { zh: '刀', py: 'dāo', en: 'knife' },
        { zh: '钥匙', py: 'yàoshi', en: 'key' },
        { zh: '镜子', py: 'jìngzi', en: 'mirror' },
        { zh: '沙发', py: 'shāfā', en: 'sofa' },
        { zh: '电视', py: 'diànshì', en: 'television' }
      ],
      [
        { zh: '浴室', py: 'yùshì', en: 'bathroom' },
        { zh: '阳台', py: 'yángtái', en: 'balcony' },
        { zh: '楼梯', py: 'lóutī', en: 'stairs' },
        { zh: '屋顶', py: 'wūdǐng', en: 'roof' },
        { zh: '花园', py: 'huāyuán', en: 'garden' },
        { zh: '车库', py: 'chēkù', en: 'garage' },
        { zh: '冰箱', py: 'bīngxiāng', en: 'refrigerator' },
        { zh: '洗衣机', py: 'xǐyījī', en: 'washing machine' },
        { zh: '空调', py: 'kōngtiáo', en: 'air conditioner' },
        { zh: '微波炉', py: 'wēibōlú', en: 'microwave' },
        { zh: '烤箱', py: 'kǎoxiāng', en: 'oven' },
        { zh: '毛巾', py: 'máojīn', en: 'towel' },
        { zh: '牙刷', py: 'yáshuā', en: 'toothbrush' },
        { zh: '肥皂', py: 'féizào', en: 'soap' },
        { zh: '枕头', py: 'zhěntou', en: 'pillow' },
        { zh: '被子', py: 'bèizi', en: 'quilt' },
        { zh: '毯子', py: 'tǎnzi', en: 'blanket' },
        { zh: '窗帘', py: 'chuānglián', en: 'curtain' },
        { zh: '地毯', py: 'dìtǎn', en: 'carpet' },
        { zh: '衣柜', py: 'yīguì', en: 'wardrobe' },
        { zh: '书架', py: 'shūjià', en: 'bookshelf' },
        { zh: '抽屉', py: 'chōuti', en: 'drawer' },
        { zh: '插座', py: 'chāzuò', en: 'power socket' },
        { zh: '楼上', py: 'lóushàng', en: 'upstairs' },
        { zh: '楼下', py: 'lóuxià', en: 'downstairs' }
      ],
      [
        { zh: '公寓', py: 'gōngyù', en: 'apartment' },
        { zh: '别墅', py: 'biéshù', en: 'villa' },
        { zh: '房东', py: 'fángdōng', en: 'landlord' },
        { zh: '租金', py: 'zūjīn', en: 'rent' },
        { zh: '搬家', py: 'bānjiā', en: 'to move house' },
        { zh: '装修', py: 'zhuāngxiū', en: 'to renovate' },
        { zh: '家具', py: 'jiājù', en: 'furniture' },
        { zh: '电器', py: 'diànqì', en: 'appliance' },
        { zh: '打扫', py: 'dǎsǎo', en: 'to clean up' },
        { zh: '整理', py: 'zhěnglǐ', en: 'to tidy' },
        { zh: '修理', py: 'xiūlǐ', en: 'to repair' },
        { zh: '漏水', py: 'lòushuǐ', en: 'to leak water' },
        { zh: '停电', py: 'tíngdiàn', en: 'power outage' },
        { zh: '暖气', py: 'nuǎnqì', en: 'heating' },
        { zh: '通风', py: 'tōngfēng', en: 'ventilation' },
        { zh: '门铃', py: 'ménlíng', en: 'doorbell' },
        { zh: '物业', py: 'wùyè', en: 'property management' },
        { zh: '角落', py: 'jiǎoluò', en: 'corner' },
        { zh: '天花板', py: 'tiānhuābǎn', en: 'ceiling' },
        { zh: '车位', py: 'chēwèi', en: 'parking space' },
        { zh: '仓库', py: 'cāngkù', en: 'storeroom' },
        { zh: '舒适', py: 'shūshì', en: 'comfortable' },
        { zh: '宽敞', py: 'kuānchang', en: 'spacious' },
        { zh: '温馨', py: 'wēnxīn', en: 'cozy' },
        { zh: '水龙头', py: 'shuǐlóngtóu', en: 'faucet' }
      ]
    ]
  },
  {
    id: 'dongci',
    name: 'Verbs',
    emoji: '🏃',
    stages: [
      [
        { zh: '是', py: 'shì', en: 'to be' },
        { zh: '有', py: 'yǒu', en: 'to have' },
        { zh: '去', py: 'qù', en: 'to go' },
        { zh: '来', py: 'lái', en: 'to come' },
        { zh: '看', py: 'kàn', en: 'to look' },
        { zh: '听', py: 'tīng', en: 'to listen' },
        { zh: '说', py: 'shuō', en: 'to speak' },
        { zh: '做', py: 'zuò', en: 'to do' },
        { zh: '想', py: 'xiǎng', en: 'to think' },
        { zh: '要', py: 'yào', en: 'to want' },
        { zh: '给', py: 'gěi', en: 'to give' },
        { zh: '走', py: 'zǒu', en: 'to walk' },
        { zh: '跑', py: 'pǎo', en: 'to run' },
        { zh: '坐', py: 'zuò', en: 'to sit' },
        { zh: '站', py: 'zhàn', en: 'to stand' },
        { zh: '睡', py: 'shuì', en: 'to sleep' },
        { zh: '开', py: 'kāi', en: 'to open' },
        { zh: '关', py: 'guān', en: 'to close' },
        { zh: '读', py: 'dú', en: 'to read' },
        { zh: '写', py: 'xiě', en: 'to write' },
        { zh: '学', py: 'xué', en: 'to study' },
        { zh: '教', py: 'jiāo', en: 'to teach' },
        { zh: '知道', py: 'zhīdào', en: 'to know' },
        { zh: '喜欢', py: 'xǐhuan', en: 'to like' },
        { zh: '帮', py: 'bāng', en: 'to help' }
      ],
      [
        { zh: '拿', py: 'ná', en: 'to take hold of' },
        { zh: '放', py: 'fàng', en: 'to put down' },
        { zh: '找', py: 'zhǎo', en: 'to look for' },
        { zh: '等', py: 'děng', en: 'to wait' },
        { zh: '问', py: 'wèn', en: 'to ask' },
        { zh: '回答', py: 'huídá', en: 'to answer' },
        { zh: '带', py: 'dài', en: 'to bring' },
        { zh: '送', py: 'sòng', en: 'to give as a gift' },
        { zh: '用', py: 'yòng', en: 'to use' },
        { zh: '穿', py: 'chuān', en: 'to wear' },
        { zh: '换', py: 'huàn', en: 'to exchange' },
        { zh: '洗', py: 'xǐ', en: 'to wash' },
        { zh: '进', py: 'jìn', en: 'to enter' },
        { zh: '出', py: 'chū', en: 'to exit' },
        { zh: '回', py: 'huí', en: 'to return' },
        { zh: '停', py: 'tíng', en: 'to stop' },
        { zh: '开始', py: 'kāishǐ', en: 'to begin' },
        { zh: '结束', py: 'jiéshù', en: 'to end' },
        { zh: '继续', py: 'jìxù', en: 'to continue' },
        { zh: '试', py: 'shì', en: 'to try' },
        { zh: '选', py: 'xuǎn', en: 'to choose' },
        { zh: '决定', py: 'juédìng', en: 'to decide' },
        { zh: '忘', py: 'wàng', en: 'to forget' },
        { zh: '记得', py: 'jìde', en: 'to remember' },
        { zh: '希望', py: 'xīwàng', en: 'to hope' }
      ],
      [
        { zh: '建立', py: 'jiànlì', en: 'to establish' },
        { zh: '改变', py: 'gǎibiàn', en: 'to change' },
        { zh: '提高', py: 'tígāo', en: 'to improve' },
        { zh: '减少', py: 'jiǎnshǎo', en: 'to reduce' },
        { zh: '增加', py: 'zēngjiā', en: 'to increase' },
        { zh: '避免', py: 'bìmiǎn', en: 'to avoid' },
        { zh: '接受', py: 'jiēshòu', en: 'to accept' },
        { zh: '拒绝', py: 'jùjué', en: 'to refuse' },
        { zh: '承认', py: 'chéngrèn', en: 'to admit' },
        { zh: '否认', py: 'fǒurèn', en: 'to deny' },
        { zh: '坚持', py: 'jiānchí', en: 'to persist' },
        { zh: '放弃', py: 'fàngqì', en: 'to give up' },
        { zh: '实现', py: 'shíxiàn', en: 'to realize a goal' },
        { zh: '完成', py: 'wánchéng', en: 'to complete' },
        { zh: '准备', py: 'zhǔnbèi', en: 'to prepare' },
        { zh: '安排', py: 'ānpái', en: 'to arrange' },
        { zh: '处理', py: 'chǔlǐ', en: 'to handle' },
        { zh: '解决', py: 'jiějué', en: 'to solve' },
        { zh: '影响', py: 'yǐngxiǎng', en: 'to affect' },
        { zh: '支持', py: 'zhīchí', en: 'to support' },
        { zh: '反对', py: 'fǎnduì', en: 'to oppose' },
        { zh: '比较', py: 'bǐjiào', en: 'to compare' },
        { zh: '包括', py: 'bāokuò', en: 'to include' },
        { zh: '需要', py: 'xūyào', en: 'to need' },
        { zh: '发现', py: 'fāxiàn', en: 'to discover' }
      ]
    ]
  },
  {
    id: 'lvxing',
    name: 'Travel',
    emoji: '✈️',
    stages: [
      [
        { zh: '车', py: 'chē', en: 'vehicle' },
        { zh: '火车', py: 'huǒchē', en: 'train' },
        { zh: '飞机', py: 'fēijī', en: 'airplane' },
        { zh: '公交车', py: 'gōngjiāochē', en: 'bus' },
        { zh: '地铁', py: 'dìtiě', en: 'subway' },
        { zh: '出租车', py: 'chūzūchē', en: 'taxi' },
        { zh: '自行车', py: 'zìxíngchē', en: 'bicycle' },
        { zh: '船', py: 'chuán', en: 'boat' },
        { zh: '路', py: 'lù', en: 'road' },
        { zh: '票', py: 'piào', en: 'ticket' },
        { zh: '机场', py: 'jīchǎng', en: 'airport' },
        { zh: '车站', py: 'chēzhàn', en: 'station' },
        { zh: '旅行', py: 'lǚxíng', en: 'to travel' },
        { zh: '到', py: 'dào', en: 'to arrive' },
        { zh: '地图', py: 'dìtú', en: 'map' },
        { zh: '行李', py: 'xíngli', en: 'luggage' },
        { zh: '护照', py: 'hùzhào', en: 'passport' },
        { zh: '酒店', py: 'jiǔdiàn', en: 'hotel' },
        { zh: '远', py: 'yuǎn', en: 'far' },
        { zh: '近', py: 'jìn', en: 'near' },
        { zh: '快', py: 'kuài', en: 'fast' },
        { zh: '慢', py: 'màn', en: 'slow' },
        { zh: '开车', py: 'kāichē', en: 'to drive' },
        { zh: '坐车', py: 'zuòchē', en: 'to ride' },
        { zh: '旅客', py: 'lǚkè', en: 'passenger' }
      ],
      [
        { zh: '签证', py: 'qiānzhèng', en: 'visa' },
        { zh: '海关', py: 'hǎiguān', en: 'customs' },
        { zh: '登机', py: 'dēngjī', en: 'to board a plane' },
        { zh: '起飞', py: 'qǐfēi', en: 'to take off' },
        { zh: '降落', py: 'jiàngluò', en: 'to land' },
        { zh: '航班', py: 'hángbān', en: 'flight' },
        { zh: '座位', py: 'zuòwèi', en: 'seat' },
        { zh: '车票', py: 'chēpiào', en: 'travel ticket' },
        { zh: '单程', py: 'dānchéng', en: 'one way' },
        { zh: '往返', py: 'wǎngfǎn', en: 'round trip' },
        { zh: '预订', py: 'yùdìng', en: 'to book' },
        { zh: '入住', py: 'rùzhù', en: 'to check in' },
        { zh: '退房', py: 'tuìfáng', en: 'to check out' },
        { zh: '导游', py: 'dǎoyóu', en: 'tour guide' },
        { zh: '景点', py: 'jǐngdiǎn', en: 'scenic spot' },
        { zh: '纪念品', py: 'jìniànpǐn', en: 'souvenir' },
        { zh: '地址', py: 'dìzhǐ', en: 'address' },
        { zh: '方向', py: 'fāngxiàng', en: 'direction' },
        { zh: '迷路', py: 'mílù', en: 'to get lost' },
        { zh: '出发', py: 'chūfā', en: 'to set out' },
        { zh: '到达', py: 'dàodá', en: 'to arrive at' },
        { zh: '延误', py: 'yánwù', en: 'to be delayed' },
        { zh: '换乘', py: 'huànchéng', en: 'to transfer' },
        { zh: '高速', py: 'gāosù', en: 'expressway' },
        { zh: '加油站', py: 'jiāyóuzhàn', en: 'gas station' }
      ],
      [
        { zh: '旅程', py: 'lǚchéng', en: 'journey' },
        { zh: '行程', py: 'xíngchéng', en: 'itinerary' },
        { zh: '目的地', py: 'mùdìdì', en: 'destination' },
        { zh: '边境', py: 'biānjìng', en: 'border' },
        { zh: '移民', py: 'yímín', en: 'immigration' },
        { zh: '托运', py: 'tuōyùn', en: 'to check baggage' },
        { zh: '随身', py: 'suíshēn', en: 'carry-on' },
        { zh: '安检', py: 'ānjiǎn', en: 'security check' },
        { zh: '中转', py: 'zhōngzhuǎn', en: 'transit' },
        { zh: '时差', py: 'shíchā', en: 'time difference' },
        { zh: '旅游', py: 'lǚyóu', en: 'tourism' },
        { zh: '背包', py: 'bēibāo', en: 'backpack' },
        { zh: '帐篷', py: 'zhàngpeng', en: 'tent' },
        { zh: '露营', py: 'lùyíng', en: 'to camp' },
        { zh: '渡轮', py: 'dùlún', en: 'ferry' },
        { zh: '缆车', py: 'lǎnchē', en: 'cable car' },
        { zh: '租车', py: 'zūchē', en: 'to rent a car' },
        { zh: '保险', py: 'bǎoxiǎn', en: 'insurance' },
        { zh: '汇率', py: 'huìlǜ', en: 'exchange rate' },
        { zh: '当地', py: 'dāngdì', en: 'local' },
        { zh: '风景', py: 'fēngjǐng', en: 'scenery' },
        { zh: '名胜', py: 'míngshèng', en: 'famous site' },
        { zh: '游客', py: 'yóukè', en: 'tourist' },
        { zh: '路线', py: 'lùxiàn', en: 'route' },
        { zh: '住宿', py: 'zhùsù', en: 'accommodation' }
      ]
    ]
  },
  {
    id: 'shenti',
    name: 'The Body',
    emoji: '🖐️',
    stages: [
      [
        { zh: '身体', py: 'shēntǐ', en: 'body' },
        { zh: '头', py: 'tóu', en: 'head' },
        { zh: '脸', py: 'liǎn', en: 'face' },
        { zh: '眼睛', py: 'yǎnjing', en: 'eye' },
        { zh: '鼻子', py: 'bízi', en: 'nose' },
        { zh: '嘴', py: 'zuǐ', en: 'mouth' },
        { zh: '耳朵', py: 'ěrduo', en: 'ear' },
        { zh: '手', py: 'shǒu', en: 'hand' },
        { zh: '脚', py: 'jiǎo', en: 'foot' },
        { zh: '腿', py: 'tuǐ', en: 'leg' },
        { zh: '胳膊', py: 'gēbo', en: 'arm' },
        { zh: '头发', py: 'tóufa', en: 'hair' },
        { zh: '牙', py: 'yá', en: 'tooth' },
        { zh: '心', py: 'xīn', en: 'heart' },
        { zh: '肚子', py: 'dùzi', en: 'belly' },
        { zh: '背', py: 'bèi', en: 'back' },
        { zh: '肩膀', py: 'jiānbǎng', en: 'shoulder' },
        { zh: '手指', py: 'shǒuzhǐ', en: 'finger' },
        { zh: '脖子', py: 'bózi', en: 'neck' },
        { zh: '皮肤', py: 'pífū', en: 'skin' },
        { zh: '血', py: 'xuè', en: 'blood' },
        { zh: '骨头', py: 'gǔtou', en: 'bone' },
        { zh: '胸', py: 'xiōng', en: 'chest' },
        { zh: '膝盖', py: 'xīgài', en: 'knee' },
        { zh: '眉毛', py: 'méimao', en: 'eyebrow' }
      ],
      [
        { zh: '胃', py: 'wèi', en: 'stomach' },
        { zh: '肺', py: 'fèi', en: 'lung' },
        { zh: '肝', py: 'gān', en: 'liver' },
        { zh: '肌肉', py: 'jīròu', en: 'muscle' },
        { zh: '神经', py: 'shénjīng', en: 'nerve' },
        { zh: '大脑', py: 'dànǎo', en: 'brain' },
        { zh: '舌头', py: 'shétou', en: 'tongue' },
        { zh: '嘴唇', py: 'zuǐchún', en: 'lip' },
        { zh: '下巴', py: 'xiàba', en: 'chin' },
        { zh: '额头', py: 'étóu', en: 'forehead' },
        { zh: '手腕', py: 'shǒuwàn', en: 'wrist' },
        { zh: '手臂', py: 'shǒubì', en: 'upper arm' },
        { zh: '脚踝', py: 'jiǎohuái', en: 'ankle' },
        { zh: '脚趾', py: 'jiǎozhǐ', en: 'toe' },
        { zh: '指甲', py: 'zhǐjia', en: 'fingernail' },
        { zh: '腰', py: 'yāo', en: 'waist' },
        { zh: '关节', py: 'guānjié', en: 'joint' },
        { zh: '血管', py: 'xuèguǎn', en: 'blood vessel' },
        { zh: '呼吸', py: 'hūxī', en: 'to breathe' },
        { zh: '心跳', py: 'xīntiào', en: 'heartbeat' },
        { zh: '体重', py: 'tǐzhòng', en: 'body weight' },
        { zh: '身高', py: 'shēngāo', en: 'body height' },
        { zh: '力气', py: 'lìqi', en: 'physical strength' },
        { zh: '姿势', py: 'zīshì', en: 'posture' },
        { zh: '汗', py: 'hàn', en: 'sweat' }
      ],
      [
        { zh: '器官', py: 'qìguān', en: 'organ' },
        { zh: '免疫', py: 'miǎnyì', en: 'immunity' },
        { zh: '细胞', py: 'xìbāo', en: 'cell' },
        { zh: '基因', py: 'jīyīn', en: 'gene' },
        { zh: '激素', py: 'jīsù', en: 'hormone' },
        { zh: '消化', py: 'xiāohuà', en: 'to digest' },
        { zh: '循环', py: 'xúnhuán', en: 'circulation' },
        { zh: '韧带', py: 'rèndài', en: 'ligament' },
        { zh: '脊椎', py: 'jǐzhuī', en: 'spine' },
        { zh: '动脉', py: 'dòngmài', en: 'artery' },
        { zh: '静脉', py: 'jìngmài', en: 'vein' },
        { zh: '肾', py: 'shèn', en: 'kidney' },
        { zh: '甲状腺', py: 'jiǎzhuàngxiàn', en: 'thyroid' },
        { zh: '视力', py: 'shìlì', en: 'eyesight' },
        { zh: '听力', py: 'tīnglì', en: 'hearing' },
        { zh: '嗅觉', py: 'xiùjué', en: 'sense of smell' },
        { zh: '味觉', py: 'wèijué', en: 'sense of taste' },
        { zh: '触觉', py: 'chùjué', en: 'sense of touch' },
        { zh: '反射', py: 'fǎnshè', en: 'reflex' },
        { zh: '平衡', py: 'pínghéng', en: 'balance' },
        { zh: '体温', py: 'tǐwēn', en: 'body temperature' },
        { zh: '脉搏', py: 'màibó', en: 'pulse' },
        { zh: '肠', py: 'cháng', en: 'intestine' },
        { zh: '腺', py: 'xiàn', en: 'gland' },
        { zh: '组织', py: 'zǔzhī', en: 'body tissue' }
      ]
    ]
  },
  {
    id: 'tianqi',
    name: 'Days & Weather',
    emoji: '☀️',
    stages: [
      [
        { zh: '天', py: 'tiān', en: 'day' },
        { zh: '今天', py: 'jīntiān', en: 'today' },
        { zh: '明天', py: 'míngtiān', en: 'tomorrow' },
        { zh: '昨天', py: 'zuótiān', en: 'yesterday' },
        { zh: '星期', py: 'xīngqī', en: 'week' },
        { zh: '月', py: 'yuè', en: 'month' },
        { zh: '年', py: 'nián', en: 'year' },
        { zh: '天气', py: 'tiānqì', en: 'weather' },
        { zh: '热', py: 'rè', en: 'hot' },
        { zh: '冷', py: 'lěng', en: 'cold' },
        { zh: '雨', py: 'yǔ', en: 'rain' },
        { zh: '雪', py: 'xuě', en: 'snow' },
        { zh: '风', py: 'fēng', en: 'wind' },
        { zh: '太阳', py: 'tàiyáng', en: 'sun' },
        { zh: '云', py: 'yún', en: 'cloud' }
      ],
      [
        { zh: '早上', py: 'zǎoshang', en: 'morning' },
        { zh: '中午', py: 'zhōngwǔ', en: 'noon' },
        { zh: '下午', py: 'xiàwǔ', en: 'afternoon' },
        { zh: '晚上', py: 'wǎnshang', en: 'evening' },
        { zh: '星期一', py: 'xīngqīyī', en: 'Monday' },
        { zh: '星期六', py: 'xīngqīliù', en: 'Saturday' },
        { zh: '星期天', py: 'xīngqītiān', en: 'Sunday' },
        { zh: '周末', py: 'zhōumò', en: 'weekend' },
        { zh: '春天', py: 'chūntiān', en: 'spring' },
        { zh: '夏天', py: 'xiàtiān', en: 'summer' },
        { zh: '秋天', py: 'qiūtiān', en: 'autumn' },
        { zh: '冬天', py: 'dōngtiān', en: 'winter' },
        { zh: '下雨', py: 'xiàyǔ', en: 'to rain' },
        { zh: '下雪', py: 'xiàxuě', en: 'to snow' },
        { zh: '晴', py: 'qíng', en: 'clear sky' },
        { zh: '阴', py: 'yīn', en: 'overcast' },
        { zh: '温暖', py: 'wēnnuǎn', en: 'warm' },
        { zh: '凉快', py: 'liángkuai', en: 'pleasantly cool' },
        { zh: '月亮', py: 'yuèliang', en: 'moon' },
        { zh: '小时', py: 'xiǎoshí', en: 'hour' }
      ],
      [
        { zh: '气候', py: 'qìhòu', en: 'climate' },
        { zh: '气温', py: 'qìwēn', en: 'air temperature' },
        { zh: '湿度', py: 'shīdù', en: 'humidity' },
        { zh: '预报', py: 'yùbào', en: 'forecast' },
        { zh: '台风', py: 'táifēng', en: 'typhoon' },
        { zh: '暴雨', py: 'bàoyǔ', en: 'rainstorm' },
        { zh: '雷', py: 'léi', en: 'thunder' },
        { zh: '闪电', py: 'shǎndiàn', en: 'lightning' },
        { zh: '雾', py: 'wù', en: 'fog' },
        { zh: '霜', py: 'shuāng', en: 'frost' },
        { zh: '冰', py: 'bīng', en: 'ice' },
        { zh: '潮湿', py: 'cháoshī', en: 'damp' },
        { zh: '干燥', py: 'gānzào', en: 'dry' },
        { zh: '闷热', py: 'mēnrè', en: 'muggy' },
        { zh: '寒冷', py: 'hánlěng', en: 'freezing' },
        { zh: '炎热', py: 'yánrè', en: 'scorching' },
        { zh: '微风', py: 'wēifēng', en: 'breeze' },
        { zh: '阵雨', py: 'zhènyǔ', en: 'shower' },
        { zh: '彩虹', py: 'cǎihóng', en: 'rainbow' },
        { zh: '日出', py: 'rìchū', en: 'sunrise' },
        { zh: '日落', py: 'rìluò', en: 'sunset' },
        { zh: '季节', py: 'jìjié', en: 'season' },
        { zh: '世纪', py: 'shìjì', en: 'century' },
        { zh: '日期', py: 'rìqī', en: 'date' },
        { zh: '分钟', py: 'fēnzhōng', en: 'minute' }
      ]
    ]
  },
  {
    id: 'xingrongci',
    name: 'Adjectives',
    emoji: '🎨',
    stages: [
      [
        { zh: '大', py: 'dà', en: 'big' },
        { zh: '小', py: 'xiǎo', en: 'small' },
        { zh: '好', py: 'hǎo', en: 'good' },
        { zh: '坏', py: 'huài', en: 'bad' },
        { zh: '新', py: 'xīn', en: 'new' },
        { zh: '旧', py: 'jiù', en: 'worn out' },
        { zh: '长', py: 'cháng', en: 'long' },
        { zh: '短', py: 'duǎn', en: 'short in length' },
        { zh: '高', py: 'gāo', en: 'tall' },
        { zh: '矮', py: 'ǎi', en: 'short in height' },
        { zh: '干净', py: 'gānjìng', en: 'clean' },
        { zh: '脏', py: 'zāng', en: 'dirty' },
        { zh: '漂亮', py: 'piàoliang', en: 'pretty' },
        { zh: '难看', py: 'nánkàn', en: 'ugly' },
        { zh: '容易', py: 'róngyì', en: 'easy' },
        { zh: '难', py: 'nán', en: 'difficult' },
        { zh: '重', py: 'zhòng', en: 'heavy' },
        { zh: '轻', py: 'qīng', en: 'light in weight' },
        { zh: '胖', py: 'pàng', en: 'fat' },
        { zh: '瘦', py: 'shòu', en: 'thin' },
        { zh: '强', py: 'qiáng', en: 'strong' },
        { zh: '弱', py: 'ruò', en: 'weak' },
        { zh: '满', py: 'mǎn', en: 'full' },
        { zh: '忙', py: 'máng', en: 'busy' },
        { zh: '累', py: 'lèi', en: 'tired' }
      ],
      [
        { zh: '安静', py: 'ānjìng', en: 'quiet' },
        { zh: '吵', py: 'chǎo', en: 'noisy' },
        { zh: '亮', py: 'liàng', en: 'bright' },
        { zh: '暗', py: 'àn', en: 'dim' },
        { zh: '软', py: 'ruǎn', en: 'soft' },
        { zh: '硬', py: 'yìng', en: 'hard' },
        { zh: '厚', py: 'hòu', en: 'thick' },
        { zh: '薄', py: 'báo', en: 'thin and flat' },
        { zh: '宽', py: 'kuān', en: 'wide' },
        { zh: '窄', py: 'zhǎi', en: 'narrow' },
        { zh: '深', py: 'shēn', en: 'deep' },
        { zh: '浅', py: 'qiǎn', en: 'shallow' },
        { zh: '圆', py: 'yuán', en: 'round' },
        { zh: '直', py: 'zhí', en: 'straight' },
        { zh: '弯', py: 'wān', en: 'bent' },
        { zh: '空', py: 'kōng', en: 'empty' },
        { zh: '危险', py: 'wēixiǎn', en: 'dangerous' },
        { zh: '安全', py: 'ānquán', en: 'safe' },
        { zh: '重要', py: 'zhòngyào', en: 'important' },
        { zh: '有趣', py: 'yǒuqù', en: 'interesting' },
        { zh: '无聊', py: 'wúliáo', en: 'boring' },
        { zh: '奇怪', py: 'qíguài', en: 'strange' },
        { zh: '普通', py: 'pǔtōng', en: 'ordinary' },
        { zh: '特别', py: 'tèbié', en: 'special' },
        { zh: '正确', py: 'zhèngquè', en: 'correct' }
      ],
      [
        { zh: '优秀', py: 'yōuxiù', en: 'excellent' },
        { zh: '糟糕', py: 'zāogāo', en: 'terrible' },
        { zh: '复杂', py: 'fùzá', en: 'complicated' },
        { zh: '简单', py: 'jiǎndān', en: 'simple' },
        { zh: '明显', py: 'míngxiǎn', en: 'obvious' },
        { zh: '模糊', py: 'móhu', en: 'blurry' },
        { zh: '准确', py: 'zhǔnquè', en: 'accurate' },
        { zh: '粗糙', py: 'cūcāo', en: 'rough' },
        { zh: '光滑', py: 'guānghuá', en: 'smooth' },
        { zh: '灵活', py: 'línghuó', en: 'flexible' },
        { zh: '僵硬', py: 'jiāngyìng', en: 'stiff' },
        { zh: '丰富', py: 'fēngfù', en: 'abundant' },
        { zh: '稳定', py: 'wěndìng', en: 'stable' },
        { zh: '剧烈', py: 'jùliè', en: 'intense' },
        { zh: '温和', py: 'wēnhé', en: 'mild' },
        { zh: '严格', py: 'yángé', en: 'strict' },
        { zh: '宽松', py: 'kuānsōng', en: 'loose' },
        { zh: '昂贵', py: 'ángguì', en: 'costly' },
        { zh: '廉价', py: 'liánjià', en: 'low-priced' },
        { zh: '陈旧', py: 'chénjiù', en: 'outdated' },
        { zh: '时髦', py: 'shímáo', en: 'fashionable' },
        { zh: '纯', py: 'chún', en: 'pure' },
        { zh: '浓', py: 'nóng', en: 'concentrated' },
        { zh: '淡', py: 'dàn', en: 'bland' },
        { zh: '巨大', py: 'jùdà', en: 'enormous' }
      ]
    ]
  },
  {
    id: 'jiaren',
    name: 'Family & People',
    emoji: '👪',
    stages: [
      [
        { zh: '妈妈', py: 'māma', en: 'mom' },
        { zh: '爸爸', py: 'bàba', en: 'dad' },
        { zh: '儿子', py: 'érzi', en: 'son' },
        { zh: '女儿', py: "nǚ'ér", en: 'daughter' },
        { zh: '哥哥', py: 'gēge', en: 'older brother' },
        { zh: '弟弟', py: 'dìdi', en: 'younger brother' },
        { zh: '姐姐', py: 'jiějie', en: 'older sister' },
        { zh: '妹妹', py: 'mèimei', en: 'younger sister' },
        { zh: '爷爷', py: 'yéye', en: "father's father" },
        { zh: '奶奶', py: 'nǎinai', en: "father's mother" },
        { zh: '人', py: 'rén', en: 'person' },
        { zh: '男人', py: 'nánrén', en: 'man' },
        { zh: '女人', py: 'nǚrén', en: 'woman' },
        { zh: '孩子', py: 'háizi', en: 'child' },
        { zh: '朋友', py: 'péngyou', en: 'friend' },
        { zh: '老师', py: 'lǎoshī', en: 'teacher' },
        { zh: '学生', py: 'xuésheng', en: 'student' },
        { zh: '名字', py: 'míngzi', en: 'name' },
        { zh: '我', py: 'wǒ', en: 'I' },
        { zh: '你', py: 'nǐ', en: 'you' },
        { zh: '他', py: 'tā', en: 'he' },
        { zh: '她', py: 'tā', en: 'she' },
        { zh: '我们', py: 'wǒmen', en: 'we' },
        { zh: '家人', py: 'jiārén', en: 'family member' },
        { zh: '男孩', py: 'nánhái', en: 'boy' }
      ],
      [
        { zh: '外公', py: 'wàigōng', en: "mother's father" },
        { zh: '外婆', py: 'wàipó', en: "mother's mother" },
        { zh: '丈夫', py: 'zhàngfu', en: 'husband' },
        { zh: '妻子', py: 'qīzi', en: 'wife' },
        { zh: '叔叔', py: 'shūshu', en: 'uncle' },
        { zh: '阿姨', py: 'āyí', en: 'aunt' },
        { zh: '邻居', py: 'línjū', en: 'neighbor' },
        { zh: '同事', py: 'tóngshì', en: 'colleague' },
        { zh: '大家', py: 'dàjiā', en: 'everyone' },
        { zh: '自己', py: 'zìjǐ', en: 'oneself' },
        { zh: '先生', py: 'xiānsheng', en: 'mister' },
        { zh: '女士', py: 'nǚshì', en: 'madam' },
        { zh: '年轻', py: 'niánqīng', en: 'young' },
        { zh: '认识', py: 'rènshi', en: 'to know someone' },
        { zh: '女孩', py: 'nǚhái', en: 'girl' },
        { zh: '父母', py: 'fùmǔ', en: 'parents' },
        { zh: '亲戚', py: 'qīnqi', en: 'relative' },
        { zh: '表哥', py: 'biǎogē', en: 'older male cousin' },
        { zh: '儿童', py: 'értóng', en: 'children' },
        { zh: '青年', py: 'qīngnián', en: 'young adult' },
        { zh: '成人', py: 'chéngrén', en: 'adult' },
        { zh: '老人', py: 'lǎorén', en: 'elderly person' },
        { zh: '同学', py: 'tóngxué', en: 'classmate' },
        { zh: '老板', py: 'lǎobǎn', en: 'boss' },
        { zh: '客人', py: 'kèrén', en: 'guest' }
      ],
      [
        { zh: '祖先', py: 'zǔxiān', en: 'ancestor' },
        { zh: '后代', py: 'hòudài', en: 'descendant' },
        { zh: '结婚', py: 'jiéhūn', en: 'to marry' },
        { zh: '离婚', py: 'líhūn', en: 'to divorce' },
        { zh: '怀孕', py: 'huáiyùn', en: 'to be pregnant' },
        { zh: '出生', py: 'chūshēng', en: 'to be born' },
        { zh: '去世', py: 'qùshì', en: 'to pass away' },
        { zh: '养育', py: 'yǎngyù', en: 'to raise a child' },
        { zh: '收养', py: 'shōuyǎng', en: 'to adopt' },
        { zh: '继父', py: 'jìfù', en: 'stepfather' },
        { zh: '双胞胎', py: 'shuāngbāotāi', en: 'twins' },
        { zh: '家庭', py: 'jiātíng', en: 'household' },
        { zh: '亲密', py: 'qīnmì', en: 'close in relationship' },
        { zh: '陌生人', py: 'mòshēngrén', en: 'stranger' },
        { zh: '熟人', py: 'shúrén', en: 'acquaintance' },
        { zh: '伴侣', py: 'bànlǚ', en: 'partner' },
        { zh: '辈分', py: 'bèifèn', en: 'family seniority' },
        { zh: '血缘', py: 'xuèyuán', en: 'blood relation' },
        { zh: '性别', py: 'xìngbié', en: 'gender' },
        { zh: '年龄', py: 'niánlíng', en: 'age' },
        { zh: '身份', py: 'shēnfèn', en: 'identity' },
        { zh: '国籍', py: 'guójí', en: 'nationality' },
        { zh: '姓', py: 'xìng', en: 'surname' },
        { zh: '独生子女', py: 'dúshēngzǐnǚ', en: 'only child' },
        { zh: '未婚妻', py: 'wèihūnqī', en: 'fiancée' }
      ]
    ]
  },
  {
    id: 'shuzi',
    name: 'Numbers & Money',
    emoji: '💴',
    stages: [
      [
        { zh: '一', py: 'yī', en: 'one' },
        { zh: '二', py: 'èr', en: 'two' },
        { zh: '三', py: 'sān', en: 'three' },
        { zh: '四', py: 'sì', en: 'four' },
        { zh: '五', py: 'wǔ', en: 'five' },
        { zh: '六', py: 'liù', en: 'six' },
        { zh: '七', py: 'qī', en: 'seven' },
        { zh: '八', py: 'bā', en: 'eight' },
        { zh: '九', py: 'jiǔ', en: 'nine' },
        { zh: '十', py: 'shí', en: 'ten' },
        { zh: '零', py: 'líng', en: 'zero' },
        { zh: '百', py: 'bǎi', en: 'hundred' },
        { zh: '千', py: 'qiān', en: 'thousand' },
        { zh: '钱', py: 'qián', en: 'money' },
        { zh: '两', py: 'liǎng', en: 'two of something' }
      ],
      [
        { zh: '万', py: 'wàn', en: 'ten thousand' },
        { zh: '块', py: 'kuài', en: 'yuan (spoken)' },
        { zh: '元', py: 'yuán', en: 'yuan (written)' },
        { zh: '贵', py: 'guì', en: 'expensive' },
        { zh: '便宜', py: 'piányi', en: 'cheap' },
        { zh: '买', py: 'mǎi', en: 'to buy' },
        { zh: '卖', py: 'mài', en: 'to sell' },
        { zh: '价格', py: 'jiàgé', en: 'price' },
        { zh: '多少', py: 'duōshao', en: 'how much' },
        { zh: '几', py: 'jǐ', en: 'how many' },
        { zh: '半', py: 'bàn', en: 'half' },
        { zh: '双', py: 'shuāng', en: 'a pair' },
        { zh: '第一', py: 'dìyī', en: 'first' },
        { zh: '免费', py: 'miǎnfèi', en: 'free of charge' },
        { zh: '银行', py: 'yínháng', en: 'bank' },
        { zh: '现金', py: 'xiànjīn', en: 'cash' },
        { zh: '个', py: 'gè', en: 'general measure word' },
        { zh: '一共', py: 'yígòng', en: 'altogether' },
        { zh: '数字', py: 'shùzì', en: 'number' },
        { zh: '付', py: 'fù', en: 'to pay' }
      ],
      [
        { zh: '信用卡', py: 'xìnyòngkǎ', en: 'credit card' },
        { zh: '找钱', py: 'zhǎoqián', en: 'to give change' },
        { zh: '发票', py: 'fāpiào', en: 'receipt' },
        { zh: '账单', py: 'zhàngdān', en: 'the bill' },
        { zh: '存款', py: 'cúnkuǎn', en: 'bank deposit' },
        { zh: '取款', py: 'qǔkuǎn', en: 'withdrawal' },
        { zh: '利息', py: 'lìxī', en: 'interest' },
        { zh: '贷款', py: 'dàikuǎn', en: 'loan' },
        { zh: '债务', py: 'zhàiwù', en: 'debt' },
        { zh: '预算', py: 'yùsuàn', en: 'budget' },
        { zh: '账户', py: 'zhànghù', en: 'account' },
        { zh: '转账', py: 'zhuǎnzhàng', en: 'bank transfer' },
        { zh: '税', py: 'shuì', en: 'tax' },
        { zh: '工资', py: 'gōngzī', en: 'wages' },
        { zh: '奖金', py: 'jiǎngjīn', en: 'bonus' },
        { zh: '折扣', py: 'zhékòu', en: 'discount' },
        { zh: '成本', py: 'chéngběn', en: 'cost' },
        { zh: '利润', py: 'lìrùn', en: 'profit' },
        { zh: '投资', py: 'tóuzī', en: 'investment' },
        { zh: '股票', py: 'gǔpiào', en: 'stock' },
        { zh: '货币', py: 'huòbì', en: 'currency' },
        { zh: '零钱', py: 'língqián', en: 'small change' },
        { zh: '支付', py: 'zhīfù', en: 'to pay out' },
        { zh: '消费', py: 'xiāofèi', en: 'to spend' },
        { zh: '省钱', py: 'shěngqián', en: 'to save money' }
      ]
    ]
  },
  {
    id: 'gongzuo',
    name: 'Work & School',
    emoji: '📚',
    stages: [
      [
        { zh: '工作', py: 'gōngzuò', en: 'work' },
        { zh: '学校', py: 'xuéxiào', en: 'school' },
        { zh: '书', py: 'shū', en: 'book' },
        { zh: '笔', py: 'bǐ', en: 'pen' },
        { zh: '纸', py: 'zhǐ', en: 'paper' },
        { zh: '课', py: 'kè', en: 'lesson' },
        { zh: '作业', py: 'zuòyè', en: 'homework' },
        { zh: '考试', py: 'kǎoshì', en: 'exam' },
        { zh: '问题', py: 'wèntí', en: 'question' },
        { zh: '答案', py: "dá'àn", en: 'answer' },
        { zh: '教室', py: 'jiàoshì', en: 'classroom' },
        { zh: '办公室', py: 'bàngōngshì', en: 'office' },
        { zh: '公司', py: 'gōngsī', en: 'company' },
        { zh: '经理', py: 'jīnglǐ', en: 'manager' },
        { zh: '会议', py: 'huìyì', en: 'meeting' },
        { zh: '电脑', py: 'diànnǎo', en: 'computer' },
        { zh: '字', py: 'zì', en: 'written character' },
        { zh: '词', py: 'cí', en: 'word' },
        { zh: '语言', py: 'yǔyán', en: 'language' },
        { zh: '中文', py: 'Zhōngwén', en: 'Chinese language' },
        { zh: '英文', py: 'Yīngwén', en: 'English language' },
        { zh: '数学', py: 'shùxué', en: 'mathematics' },
        { zh: '上课', py: 'shàngkè', en: 'to attend class' },
        { zh: '下课', py: 'xiàkè', en: 'class ends' },
        { zh: '学习', py: 'xuéxí', en: 'to study' }
      ],
      [
        { zh: '职业', py: 'zhíyè', en: 'occupation' },
        { zh: '面试', py: 'miànshì', en: 'job interview' },
        { zh: '简历', py: 'jiǎnlì', en: 'resume' },
        { zh: '合同', py: 'hétong', en: 'contract' },
        { zh: '同意', py: 'tóngyì', en: 'to agree' },
        { zh: '报告', py: 'bàogào', en: 'report' },
        { zh: '项目', py: 'xiàngmù', en: 'project' },
        { zh: '任务', py: 'rènwu', en: 'task' },
        { zh: '计划', py: 'jìhuà', en: 'plan' },
        { zh: '成绩', py: 'chéngjì', en: 'grades' },
        { zh: '毕业', py: 'bìyè', en: 'to graduate' },
        { zh: '大学', py: 'dàxué', en: 'university' },
        { zh: '中学', py: 'zhōngxué', en: 'middle school' },
        { zh: '小学', py: 'xiǎoxué', en: 'primary school' },
        { zh: '专业', py: 'zhuānyè', en: 'academic major' },
        { zh: '课程', py: 'kèchéng', en: 'course' },
        { zh: '教授', py: 'jiàoshòu', en: 'professor' },
        { zh: '校长', py: 'xiàozhǎng', en: 'principal' },
        { zh: '图书馆', py: 'túshūguǎn', en: 'library' },
        { zh: '食堂', py: 'shítáng', en: 'canteen' },
        { zh: '宿舍', py: 'sùshè', en: 'dormitory' },
        { zh: '黑板', py: 'hēibǎn', en: 'blackboard' },
        { zh: '铅笔', py: 'qiānbǐ', en: 'pencil' },
        { zh: '橡皮', py: 'xiàngpí', en: 'eraser' },
        { zh: '本子', py: 'běnzi', en: 'notebook' }
      ],
      [
        { zh: '晋升', py: 'jìnshēng', en: 'promotion' },
        { zh: '辞职', py: 'cízhí', en: 'to resign' },
        { zh: '解雇', py: 'jiěgù', en: 'to dismiss' },
        { zh: '加班', py: 'jiābān', en: 'to work overtime' },
        { zh: '出差', py: 'chūchāi', en: 'business trip' },
        { zh: '效率', py: 'xiàolǜ', en: 'efficiency' },
        { zh: '业绩', py: 'yèjì', en: 'work performance' },
        { zh: '团队', py: 'tuánduì', en: 'team' },
        { zh: '部门', py: 'bùmén', en: 'department' },
        { zh: '主管', py: 'zhǔguǎn', en: 'supervisor' },
        { zh: '客户', py: 'kèhù', en: 'client' },
        { zh: '市场', py: 'shìchǎng', en: 'market' },
        { zh: '销售', py: 'xiāoshòu', en: 'sales' },
        { zh: '战略', py: 'zhànlüè', en: 'strategy' },
        { zh: '截止', py: 'jiézhǐ', en: 'deadline' },
        { zh: '培训', py: 'péixùn', en: 'training' },
        { zh: '技能', py: 'jìnéng', en: 'skill' },
        { zh: '经验', py: 'jīngyàn', en: 'experience' },
        { zh: '资格', py: 'zīgé', en: 'qualification' },
        { zh: '学位', py: 'xuéwèi', en: 'academic degree' },
        { zh: '论文', py: 'lùnwén', en: 'thesis' },
        { zh: '研究', py: 'yánjiū', en: 'research' },
        { zh: '奖学金', py: 'jiǎngxuéjīn', en: 'scholarship' },
        { zh: '实习', py: 'shíxí', en: 'internship' },
        { zh: '供应商', py: 'gōngyìngshāng', en: 'supplier' }
      ]
    ]
  },
  {
    id: 'chengshi',
    name: 'City & Places',
    emoji: '🏙️',
    stages: [
      [
        { zh: '城市', py: 'chéngshì', en: 'city' },
        { zh: '街', py: 'jiē', en: 'street' },
        { zh: '商店', py: 'shāngdiàn', en: 'shop' },
        { zh: '医院', py: 'yīyuàn', en: 'hospital' },
        { zh: '公园', py: 'gōngyuán', en: 'park' },
        { zh: '饭馆', py: 'fànguǎn', en: 'restaurant' },
        { zh: '超市', py: 'chāoshì', en: 'supermarket' },
        { zh: '邮局', py: 'yóujú', en: 'post office' },
        { zh: '桥', py: 'qiáo', en: 'bridge' },
        { zh: '楼', py: 'lóu', en: 'multi-storey building' },
        { zh: '地方', py: 'dìfang', en: 'place' },
        { zh: '中心', py: 'zhōngxīn', en: 'center' },
        { zh: '村子', py: 'cūnzi', en: 'village' },
        { zh: '国家', py: 'guójiā', en: 'country' },
        { zh: '城', py: 'chéng', en: 'town' },
        { zh: '路口', py: 'lùkǒu', en: 'intersection' },
        { zh: '广场', py: 'guǎngchǎng', en: 'public square' },
        { zh: '门口', py: 'ménkǒu', en: 'doorway' },
        { zh: '附近', py: 'fùjìn', en: 'nearby' },
        { zh: '市区', py: 'shìqū', en: 'downtown' }
      ],
      [
        { zh: '博物馆', py: 'bówùguǎn', en: 'museum' },
        { zh: '剧院', py: 'jùyuàn', en: 'theater' },
        { zh: '电影院', py: 'diànyǐngyuàn', en: 'cinema' },
        { zh: '体育馆', py: 'tǐyùguǎn', en: 'gymnasium' },
        { zh: '教堂', py: 'jiàotáng', en: 'church' },
        { zh: '寺庙', py: 'sìmiào', en: 'temple' },
        { zh: '大使馆', py: 'dàshǐguǎn', en: 'embassy' },
        { zh: '警察局', py: 'jǐngchájú', en: 'police station' },
        { zh: '消防站', py: 'xiāofángzhàn', en: 'fire station' },
        { zh: '药店', py: 'yàodiàn', en: 'pharmacy' },
        { zh: '理发店', py: 'lǐfàdiàn', en: 'barbershop' },
        { zh: '面包店', py: 'miànbāodiàn', en: 'bakery' },
        { zh: '书店', py: 'shūdiàn', en: 'bookstore' },
        { zh: '咖啡馆', py: 'kāfēiguǎn', en: 'cafe' },
        { zh: '酒吧', py: 'jiǔbā', en: 'bar' },
        { zh: '夜市', py: 'yèshì', en: 'night market' },
        { zh: '人行道', py: 'rénxíngdào', en: 'sidewalk' },
        { zh: '红绿灯', py: 'hónglǜdēng', en: 'traffic light' },
        { zh: '停车场', py: 'tíngchēchǎng', en: 'parking lot' },
        { zh: '郊区', py: 'jiāoqū', en: 'suburb' }
      ],
      [
        { zh: '首都', py: 'shǒudū', en: 'capital city' },
        { zh: '省', py: 'shěng', en: 'province' },
        { zh: '区', py: 'qū', en: 'district' },
        { zh: '社区', py: 'shèqū', en: 'community' },
        { zh: '居民', py: 'jūmín', en: 'resident' },
        { zh: '人口', py: 'rénkǒu', en: 'population' },
        { zh: '交通', py: 'jiāotōng', en: 'traffic' },
        { zh: '拥挤', py: 'yōngjǐ', en: 'crowded' },
        { zh: '繁华', py: 'fánhuá', en: 'bustling' },
        { zh: '偏僻', py: 'piānpì', en: 'remote' },
        { zh: '公共', py: 'gōnggòng', en: 'public' },
        { zh: '设施', py: 'shèshī', en: 'facility' },
        { zh: '建筑', py: 'jiànzhù', en: 'architecture' },
        { zh: '摩天大楼', py: 'mótiāndàlóu', en: 'skyscraper' },
        { zh: '工厂', py: 'gōngchǎng', en: 'factory' },
        { zh: '码头', py: 'mǎtóu', en: 'wharf' },
        { zh: '隧道', py: 'suìdào', en: 'tunnel' },
        { zh: '高楼', py: 'gāolóu', en: 'high-rise' },
        { zh: '街区', py: 'jiēqū', en: 'city block' },
        { zh: '垃圾', py: 'lājī', en: 'garbage' }
      ]
    ]
  },
  {
    id: 'yifu',
    name: 'Clothing',
    emoji: '👕',
    stages: [
      [
        { zh: '衣服', py: 'yīfu', en: 'clothes' },
        { zh: '裤子', py: 'kùzi', en: 'trousers' },
        { zh: '裙子', py: 'qúnzi', en: 'skirt' },
        { zh: '鞋', py: 'xié', en: 'shoes' },
        { zh: '袜子', py: 'wàzi', en: 'socks' },
        { zh: '帽子', py: 'màozi', en: 'hat' },
        { zh: '外套', py: 'wàitào', en: 'coat' },
        { zh: '衬衫', py: 'chènshān', en: 'shirt' },
        { zh: '毛衣', py: 'máoyī', en: 'sweater' },
        { zh: '手套', py: 'shǒutào', en: 'gloves' },
        { zh: '围巾', py: 'wéijīn', en: 'scarf' },
        { zh: '眼镜', py: 'yǎnjìng', en: 'glasses' },
        { zh: '包', py: 'bāo', en: 'bag' },
        { zh: '钱包', py: 'qiánbāo', en: 'wallet' },
        { zh: '表', py: 'biǎo', en: 'wristwatch' },
        { zh: '戒指', py: 'jièzhi', en: 'ring' },
        { zh: '颜色', py: 'yánsè', en: 'color' },
        { zh: '红', py: 'hóng', en: 'red' },
        { zh: '蓝', py: 'lán', en: 'blue' },
        { zh: '黄', py: 'huáng', en: 'yellow' },
        { zh: '绿', py: 'lǜ', en: 'green' },
        { zh: '黑', py: 'hēi', en: 'black' },
        { zh: '白', py: 'bái', en: 'white' },
        { zh: '号', py: 'hào', en: 'size' },
        { zh: '牛仔裤', py: 'niúzǎikù', en: 'jeans' }
      ],
      [
        { zh: '内衣', py: 'nèiyī', en: 'underwear' },
        { zh: '睡衣', py: 'shuìyī', en: 'pajamas' },
        { zh: '西装', py: 'xīzhuāng', en: 'suit' },
        { zh: '领带', py: 'lǐngdài', en: 'necktie' },
        { zh: '腰带', py: 'yāodài', en: 'belt' },
        { zh: '靴子', py: 'xuēzi', en: 'boots' },
        { zh: '凉鞋', py: 'liángxié', en: 'sandals' },
        { zh: '运动鞋', py: 'yùndòngxié', en: 'sneakers' },
        { zh: '拖鞋', py: 'tuōxié', en: 'slippers' },
        { zh: '背心', py: 'bèixīn', en: 'vest' },
        { zh: '短裤', py: 'duǎnkù', en: 'shorts' },
        { zh: '连衣裙', py: 'liányīqún', en: 'dress' },
        { zh: '口袋', py: 'kǒudài', en: 'pocket' },
        { zh: '纽扣', py: 'niǔkòu', en: 'button' },
        { zh: '拉链', py: 'lāliàn', en: 'zipper' },
        { zh: '布', py: 'bù', en: 'cloth' },
        { zh: '棉', py: 'mián', en: 'cotton' },
        { zh: '丝', py: 'sī', en: 'silk' },
        { zh: '羊毛', py: 'yángmáo', en: 'wool' },
        { zh: '皮革', py: 'pígé', en: 'leather' },
        { zh: '灰', py: 'huī', en: 'gray' },
        { zh: '粉红', py: 'fěnhóng', en: 'pink' },
        { zh: '紫', py: 'zǐ', en: 'purple' },
        { zh: '橙', py: 'chéng', en: 'orange color' },
        { zh: '试穿', py: 'shìchuān', en: 'to try on' }
      ],
      [
        { zh: '时尚', py: 'shíshàng', en: 'fashion' },
        { zh: '款式', py: 'kuǎnshì', en: 'style of design' },
        { zh: '合身', py: 'héshēn', en: 'well-fitting' },
        { zh: '搭配', py: 'dāpèi', en: 'to match' },
        { zh: '优雅', py: 'yōuyǎ', en: 'elegant' },
        { zh: '朴素', py: 'pǔsù', en: 'plain' },
        { zh: '华丽', py: 'huálì', en: 'ornate' },
        { zh: '褪色', py: 'tuìsè', en: 'to fade' },
        { zh: '缩水', py: 'suōshuǐ', en: 'to shrink' },
        { zh: '熨', py: 'yùn', en: 'to iron' },
        { zh: '缝', py: 'féng', en: 'to sew' },
        { zh: '补', py: 'bǔ', en: 'to mend' },
        { zh: '干洗', py: 'gānxǐ', en: 'dry cleaning' },
        { zh: '衣领', py: 'yīlǐng', en: 'collar' },
        { zh: '袖子', py: 'xiùzi', en: 'sleeve' },
        { zh: '面料', py: 'miànliào', en: 'fabric' },
        { zh: '配饰', py: 'pèishì', en: 'accessory' },
        { zh: '项链', py: 'xiàngliàn', en: 'necklace' },
        { zh: '耳环', py: 'ěrhuán', en: 'earring' },
        { zh: '手镯', py: 'shǒuzhuó', en: 'bracelet' },
        { zh: '化妆', py: 'huàzhuāng', en: 'to put on makeup' },
        { zh: '香水', py: 'xiāngshuǐ', en: 'perfume' },
        { zh: '品牌', py: 'pǐnpái', en: 'brand' },
        { zh: '剪裁', py: 'jiǎncái', en: 'cut of a garment' },
        { zh: '整洁', py: 'zhěngjié', en: 'neat' }
      ]
    ]
  },
  {
    id: 'ganqing',
    name: 'Feelings & Mind',
    emoji: '💭',
    stages: [
      [
        { zh: '高兴', py: 'gāoxìng', en: 'happy' },
        { zh: '难过', py: 'nánguò', en: 'sad' },
        { zh: '生气', py: 'shēngqì', en: 'angry' },
        { zh: '害怕', py: 'hàipà', en: 'afraid' },
        { zh: '爱', py: 'ài', en: 'to love' },
        { zh: '恨', py: 'hèn', en: 'to hate' },
        { zh: '笑', py: 'xiào', en: 'to laugh' },
        { zh: '哭', py: 'kū', en: 'to cry' },
        { zh: '感觉', py: 'gǎnjué', en: 'feeling' },
        { zh: '心情', py: 'xīnqíng', en: 'mood' },
        { zh: '开心', py: 'kāixīn', en: 'cheerful' },
        { zh: '担心', py: 'dānxīn', en: 'to worry' },
        { zh: '惊讶', py: 'jīngyà', en: 'surprised' },
        { zh: '紧张', py: 'jǐnzhāng', en: 'nervous' },
        { zh: '放松', py: 'fàngsōng', en: 'relaxed' }
      ],
      [
        { zh: '兴奋', py: 'xīngfèn', en: 'excited' },
        { zh: '失望', py: 'shīwàng', en: 'disappointed' },
        { zh: '后悔', py: 'hòuhuǐ', en: 'to regret' },
        { zh: '嫉妒', py: 'jídù', en: 'jealous' },
        { zh: '骄傲', py: "jiāo'ào", en: 'proud' },
        { zh: '羞愧', py: 'xiūkuì', en: 'ashamed' },
        { zh: '孤独', py: 'gūdú', en: 'lonely' },
        { zh: '感动', py: 'gǎndòng', en: 'moved' },
        { zh: '满意', py: 'mǎnyì', en: 'satisfied' },
        { zh: '讨厌', py: 'tǎoyàn', en: 'to dislike' },
        { zh: '想念', py: 'xiǎngniàn', en: 'to miss someone' },
        { zh: '信任', py: 'xìnrèn', en: 'to trust' },
        { zh: '怀疑', py: 'huáiyí', en: 'to doubt' },
        { zh: '思想', py: 'sīxiǎng', en: 'thought' },
        { zh: '记忆', py: 'jìyì', en: 'memory' },
        { zh: '梦', py: 'mèng', en: 'dream' },
        { zh: '注意', py: 'zhùyì', en: 'to pay attention' },
        { zh: '理解', py: 'lǐjiě', en: 'to understand' },
        { zh: '同情', py: 'tóngqíng', en: 'sympathy' },
        { zh: '勇气', py: 'yǒngqì', en: 'courage' },
        { zh: '耐心', py: 'nàixīn', en: 'patience' },
        { zh: '脾气', py: 'píqi', en: 'temper' },
        { zh: '性格', py: 'xìnggé', en: 'personality' },
        { zh: '态度', py: 'tàidu', en: 'attitude' },
        { zh: '无奈', py: 'wúnài', en: 'resigned' }
      ],
      [
        { zh: '焦虑', py: 'jiāolǜ', en: 'anxiety' },
        { zh: '沮丧', py: 'jǔsàng', en: 'dejected' },
        { zh: '愤怒', py: 'fènnù', en: 'fury' },
        { zh: '恐惧', py: 'kǒngjù', en: 'dread' },
        { zh: '喜悦', py: 'xǐyuè', en: 'joy' },
        { zh: '悲伤', py: 'bēishāng', en: 'sorrow' },
        { zh: '冷静', py: 'lěngjìng', en: 'calm' },
        { zh: '理智', py: 'lǐzhì', en: 'rational' },
        { zh: '冲动', py: 'chōngdòng', en: 'impulsive' },
        { zh: '敏感', py: 'mǐngǎn', en: 'sensitive' },
        { zh: '自信', py: 'zìxìn', en: 'confident' },
        { zh: '自卑', py: 'zìbēi', en: 'self-abasing' },
        { zh: '乐观', py: 'lèguān', en: 'optimistic' },
        { zh: '悲观', py: 'bēiguān', en: 'pessimistic' },
        { zh: '情绪', py: 'qíngxù', en: 'emotion' },
        { zh: '意识', py: 'yìshí', en: 'consciousness' },
        { zh: '直觉', py: 'zhíjué', en: 'intuition' },
        { zh: '想象', py: 'xiǎngxiàng', en: 'to imagine' },
        { zh: '专注', py: 'zhuānzhù', en: 'to concentrate' },
        { zh: '分心', py: 'fēnxīn', en: 'distracted' },
        { zh: '压力', py: 'yālì', en: 'pressure' },
        { zh: '安慰', py: 'ānwèi', en: 'to comfort' },
        { zh: '鼓励', py: 'gǔlì', en: 'to encourage' },
        { zh: '心理', py: 'xīnlǐ', en: 'psychology' },
        { zh: '潜意识', py: 'qiányìshí', en: 'subconscious' }
      ]
    ]
  },
  {
    id: 'wenti',
    name: 'Questions & Connectors',
    emoji: '❓',
    stages: [
      [
        { zh: '什么', py: 'shénme', en: 'what' },
        { zh: '谁', py: 'shéi', en: 'who' },
        { zh: '哪', py: 'nǎ', en: 'which' },
        { zh: '哪儿', py: 'nǎr', en: 'where' },
        { zh: '为什么', py: 'wèishénme', en: 'why' },
        { zh: '怎么', py: 'zěnme', en: 'how' },
        { zh: '吗', py: 'ma', en: 'question particle' },
        { zh: '呢', py: 'ne', en: 'follow-up particle' },
        { zh: '不', py: 'bù', en: 'not' },
        { zh: '没', py: 'méi', en: 'have not' },
        { zh: '和', py: 'hé', en: 'and' },
        { zh: '但是', py: 'dànshì', en: 'but' },
        { zh: '因为', py: 'yīnwèi', en: 'because' },
        { zh: '所以', py: 'suǒyǐ', en: 'so' },
        { zh: '或者', py: 'huòzhě', en: 'or' }
      ],
      [
        { zh: '如果', py: 'rúguǒ', en: 'if' },
        { zh: '虽然', py: 'suīrán', en: 'although' },
        { zh: '可是', py: 'kěshì', en: 'however' },
        { zh: '而且', py: 'érqiě', en: 'moreover' },
        { zh: '还是', py: 'háishi', en: 'or, in a question' },
        { zh: '就', py: 'jiù', en: 'then' },
        { zh: '才', py: 'cái', en: 'only then' },
        { zh: '也', py: 'yě', en: 'also' },
        { zh: '都', py: 'dōu', en: 'all' },
        { zh: '还', py: 'hái', en: 'still' },
        { zh: '已经', py: 'yǐjīng', en: 'already' },
        { zh: '再', py: 'zài', en: 'again' },
        { zh: '又', py: 'yòu', en: 'again, in the past' },
        { zh: '很', py: 'hěn', en: 'very' },
        { zh: '太', py: 'tài', en: 'too' },
        { zh: '最', py: 'zuì', en: 'most' },
        { zh: '比', py: 'bǐ', en: 'compared to' },
        { zh: '一样', py: 'yíyàng', en: 'the same' },
        { zh: '不同', py: 'bùtóng', en: 'different' },
        { zh: '怎么样', py: 'zěnmeyàng', en: 'how about' }
      ],
      [
        { zh: '然而', py: "rán'ér", en: 'nevertheless' },
        { zh: '因此', py: 'yīncǐ', en: 'therefore' },
        { zh: '于是', py: 'yúshì', en: 'thereupon' },
        { zh: '不过', py: 'búguò', en: 'though' },
        { zh: '除非', py: 'chúfēi', en: 'unless' },
        { zh: '即使', py: 'jíshǐ', en: 'even if' },
        { zh: '无论', py: 'wúlùn', en: 'regardless' },
        { zh: '既然', py: 'jìrán', en: 'since' },
        { zh: '否则', py: 'fǒuzé', en: 'otherwise' },
        { zh: '另外', py: 'lìngwài', en: 'besides' },
        { zh: '其实', py: 'qíshí', en: 'actually' },
        { zh: '当然', py: 'dāngrán', en: 'of course' },
        { zh: '也许', py: 'yěxǔ', en: 'perhaps' },
        { zh: '可能', py: 'kěnéng', en: 'possible' },
        { zh: '一定', py: 'yídìng', en: 'certainly' },
        { zh: '大概', py: 'dàgài', en: 'roughly' },
        { zh: '究竟', py: 'jiūjìng', en: 'after all' },
        { zh: '到底', py: 'dàodǐ', en: 'in the end' },
        { zh: '反正', py: 'fǎnzhèng', en: 'anyway' },
        { zh: '尤其', py: 'yóuqí', en: 'especially' },
        { zh: '比如', py: 'bǐrú', en: 'for example' },
        { zh: '总之', py: 'zǒngzhī', en: 'in short' },
        { zh: '首先', py: 'shǒuxiān', en: 'first of all' },
        { zh: '其次', py: 'qícì', en: 'secondly' },
        { zh: '最后', py: 'zuìhòu', en: 'finally' }
      ]
    ]
  },
  {
    id: 'weizhi',
    name: 'Where Things Are',
    emoji: '🧭',
    stages: [
      [
        { zh: '上', py: 'shàng', en: 'above' },
        { zh: '下', py: 'xià', en: 'below' },
        { zh: '里', py: 'lǐ', en: 'inside' },
        { zh: '外', py: 'wài', en: 'outside' },
        { zh: '前', py: 'qián', en: 'in front' },
        { zh: '后', py: 'hòu', en: 'behind' },
        { zh: '左', py: 'zuǒ', en: 'left' },
        { zh: '右', py: 'yòu', en: 'right' },
        { zh: '中间', py: 'zhōngjiān', en: 'middle' },
        { zh: '旁边', py: 'pángbiān', en: 'beside' },
        { zh: '这里', py: 'zhèlǐ', en: 'here' },
        { zh: '那里', py: 'nàlǐ', en: 'there' },
        { zh: '东', py: 'dōng', en: 'east' },
        { zh: '南', py: 'nán', en: 'south' },
        { zh: '西', py: 'xī', en: 'west' },
        { zh: '北', py: 'běi', en: 'north' },
        { zh: '上面', py: 'shàngmiàn', en: 'on top of' },
        { zh: '下面', py: 'xiàmiàn', en: 'underneath' },
        { zh: '里面', py: 'lǐmiàn', en: 'inside of' },
        { zh: '外面', py: 'wàimiàn', en: 'outside of' }
      ],
      [
        { zh: '对面', py: 'duìmiàn', en: 'opposite' },
        { zh: '之间', py: 'zhījiān', en: 'between' },
        { zh: '周围', py: 'zhōuwéi', en: 'around' },
        { zh: '边', py: 'biān', en: 'edge' },
        { zh: '底', py: 'dǐ', en: 'bottom' },
        { zh: '顶', py: 'dǐng', en: 'top' },
        { zh: '远处', py: 'yuǎnchù', en: 'far off' },
        { zh: '近处', py: 'jìnchù', en: 'close by' },
        { zh: '到处', py: 'dàochù', en: 'everywhere' },
        { zh: '中央', py: 'zhōngyāng', en: 'central' },
        { zh: '背后', py: 'bèihòu', en: 'behind the back' },
        { zh: '前方', py: 'qiánfāng', en: 'ahead' },
        { zh: '后方', py: 'hòufāng', en: 'the rear' },
        { zh: '内部', py: 'nèibù', en: 'interior' },
        { zh: '表面', py: 'biǎomiàn', en: 'surface' },
        { zh: '水平', py: 'shuǐpíng', en: 'horizontal' },
        { zh: '垂直', py: 'chuízhí', en: 'vertical' },
        { zh: '平行', py: 'píngxíng', en: 'parallel' },
        { zh: '各处', py: 'gèchù', en: 'various places' },
        { zh: '尽头', py: 'jìntóu', en: 'the far end' }
      ],
      [
        { zh: '位置', py: 'wèizhi', en: 'position' },
        { zh: '方位', py: 'fāngwèi', en: 'bearing' },
        { zh: '距离', py: 'jùlí', en: 'distance' },
        { zh: '范围', py: 'fànwéi', en: 'range' },
        { zh: '边缘', py: 'biānyuán', en: 'margin' },
        { zh: '坐标', py: 'zuòbiāo', en: 'coordinates' },
        { zh: '朝向', py: 'cháoxiàng', en: 'to face toward' },
        { zh: '面向', py: 'miànxiàng', en: 'facing' },
        { zh: '靠近', py: 'kàojìn', en: 'to draw near' },
        { zh: '远离', py: 'yuǎnlí', en: 'to keep away from' },
        { zh: '相邻', py: 'xiānglín', en: 'adjacent' },
        { zh: '分布', py: 'fēnbù', en: 'distribution' },
        { zh: '集中', py: 'jízhōng', en: 'concentrated' },
        { zh: '分散', py: 'fēnsàn', en: 'scattered' },
        { zh: '排列', py: 'páiliè', en: 'to arrange in order' },
        { zh: '顺序', py: 'shùnxù', en: 'sequence' },
        { zh: '层', py: 'céng', en: 'layer' },
        { zh: '面积', py: 'miànjī', en: 'area' },
        { zh: '体积', py: 'tǐjī', en: 'volume' },
        { zh: '长度', py: 'chángdù', en: 'length' },
        { zh: '宽度', py: 'kuāndù', en: 'width' },
        { zh: '高度', py: 'gāodù', en: 'height' },
        { zh: '深度', py: 'shēndù', en: 'depth' },
        { zh: '角度', py: 'jiǎodù', en: 'angle' },
        { zh: '间隔', py: 'jiàngé', en: 'interval' }
      ]
    ]
  },
  {
    id: 'richang',
    name: 'Daily Routine',
    emoji: '⏰',
    stages: [
      [
        { zh: '起床', py: 'qǐchuáng', en: 'to get up' },
        { zh: '睡觉', py: 'shuìjiào', en: 'to go to sleep' },
        { zh: '刷牙', py: 'shuāyá', en: 'to brush teeth' },
        { zh: '洗澡', py: 'xǐzǎo', en: 'to bathe' },
        { zh: '上班', py: 'shàngbān', en: 'to go to work' },
        { zh: '下班', py: 'xiàbān', en: 'to finish work' },
        { zh: '回家', py: 'huíjiā', en: 'to go home' },
        { zh: '休息', py: 'xiūxi', en: 'to rest' },
        { zh: '做饭', py: 'zuòfàn', en: 'to cook' },
        { zh: '每天', py: 'měitiān', en: 'every day' },
        { zh: '时间', py: 'shíjiān', en: 'time' },
        { zh: '早', py: 'zǎo', en: 'early' },
        { zh: '晚', py: 'wǎn', en: 'late' },
        { zh: '习惯', py: 'xíguàn', en: 'habit' },
        { zh: '穿衣', py: 'chuānyī', en: 'to get dressed' }
      ],
      [
        { zh: '洗脸', py: 'xǐliǎn', en: 'to wash the face' },
        { zh: '梳头', py: 'shūtóu', en: 'to comb hair' },
        { zh: '出门', py: 'chūmén', en: 'to head out' },
        { zh: '锁门', py: 'suǒmén', en: 'to lock the door' },
        { zh: '买菜', py: 'mǎicài', en: 'to buy groceries' },
        { zh: '洗碗', py: 'xǐwǎn', en: 'to wash dishes' },
        { zh: '洗衣', py: 'xǐyī', en: 'to do laundry' },
        { zh: '遛狗', py: 'liùgǒu', en: 'to walk the dog' },
        { zh: '午睡', py: 'wǔshuì', en: 'afternoon nap' },
        { zh: '看电视', py: 'kàndiànshì', en: 'to watch television' },
        { zh: '听音乐', py: 'tīngyīnyuè', en: 'to listen to music' },
        { zh: '散步', py: 'sànbù', en: 'to take a walk' },
        { zh: '排队', py: 'páiduì', en: 'to queue' },
        { zh: '等车', py: 'děngchē', en: 'to wait for a ride' },
        { zh: '迟到', py: 'chídào', en: 'to arrive late' },
        { zh: '准时', py: 'zhǔnshí', en: 'on time' },
        { zh: '日程', py: 'rìchéng', en: 'schedule' },
        { zh: '闹钟', py: 'nàozhōng', en: 'alarm clock' },
        { zh: '睡懒觉', py: 'shuìlǎnjiào', en: 'to sleep in' },
        { zh: '忙碌', py: 'mánglù', en: 'busy with tasks' }
      ],
      [
        { zh: '作息', py: 'zuòxī', en: 'daily rhythm' },
        { zh: '规律', py: 'guīlǜ', en: 'regularity' },
        { zh: '拖延', py: 'tuōyán', en: 'to procrastinate' },
        { zh: '优先', py: 'yōuxiān', en: 'priority' },
        { zh: '日常', py: 'rìcháng', en: 'everyday' },
        { zh: '例行', py: 'lìxíng', en: 'routine' },
        { zh: '自律', py: 'zìlǜ', en: 'self-discipline' },
        { zh: '清单', py: 'qīngdān', en: 'checklist' },
        { zh: '提醒', py: 'tíxǐng', en: 'to remind' },
        { zh: '整天', py: 'zhěngtiān', en: 'all day long' },
        { zh: '偶尔', py: "ǒu'ěr", en: 'occasionally' },
        { zh: '经常', py: 'jīngcháng', en: 'often' },
        { zh: '很少', py: 'hěnshǎo', en: 'seldom' },
        { zh: '从不', py: 'cóngbù', en: 'never' },
        { zh: '总是', py: 'zǒngshì', en: 'always' },
        { zh: '有时', py: 'yǒushí', en: 'sometimes' },
        { zh: '按时', py: 'ànshí', en: 'on schedule' },
        { zh: '提前', py: 'tíqián', en: 'in advance' },
        { zh: '推迟', py: 'tuīchí', en: 'to postpone' },
        { zh: '匆忙', py: 'cōngmáng', en: 'hurried' },
        { zh: '从容', py: 'cóngróng', en: 'unhurried' },
        { zh: '熬夜', py: 'áoyè', en: 'to stay up late' },
        { zh: '早起', py: 'zǎoqǐ', en: 'to rise early' },
        { zh: '午休', py: 'wǔxiū', en: 'midday break' },
        { zh: '节奏', py: 'jiézòu', en: 'rhythm' }
      ]
    ]
  },
  {
    id: 'jiankang',
    name: 'Health & the Doctor',
    emoji: '🩺',
    stages: [
      [
        { zh: '医生', py: 'yīshēng', en: 'doctor' },
        { zh: '护士', py: 'hùshi', en: 'nurse' },
        { zh: '病', py: 'bìng', en: 'illness' },
        { zh: '药', py: 'yào', en: 'medicine' },
        { zh: '疼', py: 'téng', en: 'to hurt' },
        { zh: '发烧', py: 'fāshāo', en: 'to have a fever' },
        { zh: '感冒', py: 'gǎnmào', en: 'a cold' },
        { zh: '咳嗽', py: 'késou', en: 'to cough' },
        { zh: '头疼', py: 'tóuténg', en: 'headache' },
        { zh: '肚子疼', py: 'dùziténg', en: 'stomachache' },
        { zh: '健康', py: 'jiànkāng', en: 'health' },
        { zh: '看病', py: 'kànbìng', en: 'to see a doctor' },
        { zh: '受伤', py: 'shòushāng', en: 'to be injured' },
        { zh: '流血', py: 'liúxuè', en: 'to bleed' },
        { zh: '打针', py: 'dǎzhēn', en: 'to get an injection' },
        { zh: '血压', py: 'xuèyā', en: 'blood pressure' },
        { zh: '过敏', py: 'guòmǐn', en: 'allergy' },
        { zh: '牙疼', py: 'yáténg', en: 'toothache' },
        { zh: '嗓子', py: 'sǎngzi', en: 'throat' },
        { zh: '处方', py: 'chǔfāng', en: 'prescription' },
        { zh: '体检', py: 'tǐjiǎn', en: 'medical checkup' },
        { zh: '病人', py: 'bìngrén', en: 'patient' },
        { zh: '救护车', py: 'jiùhùchē', en: 'ambulance' },
        { zh: '急诊', py: 'jízhěn', en: 'emergency care' },
        { zh: '恢复', py: 'huīfù', en: 'to recover' }
      ],
      [
        { zh: '药片', py: 'yàopiàn', en: 'tablet' },
        { zh: '胶囊', py: 'jiāonáng', en: 'capsule' },
        { zh: '药水', py: 'yàoshuǐ', en: 'liquid medicine' },
        { zh: '绷带', py: 'bēngdài', en: 'bandage' },
        { zh: '伤口', py: 'shāngkǒu', en: 'wound' },
        { zh: '骨折', py: 'gǔzhé', en: 'bone fracture' },
        { zh: '扭伤', py: 'niǔshāng', en: 'sprain' },
        { zh: '烧伤', py: 'shāoshāng', en: 'burn injury' },
        { zh: '中暑', py: 'zhòngshǔ', en: 'heatstroke' },
        { zh: '呕吐', py: 'ǒutù', en: 'to vomit' },
        { zh: '腹泻', py: 'fùxiè', en: 'diarrhea' },
        { zh: '便秘', py: 'biànmì', en: 'constipation' },
        { zh: '失眠', py: 'shīmián', en: 'insomnia' },
        { zh: '头晕', py: 'tóuyūn', en: 'dizzy' },
        { zh: '乏力', py: 'fálì', en: 'weakness' },
        { zh: '症状', py: 'zhèngzhuàng', en: 'symptom' },
        { zh: '诊断', py: 'zhěnduàn', en: 'diagnosis' },
        { zh: '治疗', py: 'zhìliáo', en: 'treatment' },
        { zh: '手术', py: 'shǒushù', en: 'surgery' },
        { zh: '麻醉', py: 'mázuì', en: 'anesthesia' },
        { zh: '病房', py: 'bìngfáng', en: 'hospital ward' },
        { zh: '挂号', py: 'guàhào', en: 'to register at a clinic' },
        { zh: '疫苗', py: 'yìmiáo', en: 'vaccine' },
        { zh: '传染', py: 'chuánrǎn', en: 'to be contagious' },
        { zh: '细菌', py: 'xìjūn', en: 'bacteria' }
      ],
      [
        { zh: '病毒', py: 'bìngdú', en: 'virus' },
        { zh: '免疫力', py: 'miǎnyìlì', en: 'immune strength' },
        { zh: '慢性', py: 'mànxìng', en: 'chronic' },
        { zh: '急性', py: 'jíxìng', en: 'acute' },
        { zh: '遗传', py: 'yíchuán', en: 'hereditary' },
        { zh: '康复', py: 'kāngfù', en: 'rehabilitation' },
        { zh: '副作用', py: 'fùzuòyòng', en: 'side effect' },
        { zh: '剂量', py: 'jìliàng', en: 'dosage' },
        { zh: '急救', py: 'jíjiù', en: 'first aid' },
        { zh: '输血', py: 'shūxuè', en: 'blood transfusion' },
        { zh: '化验', py: 'huàyàn', en: 'lab test' },
        { zh: '拍片', py: 'pāipiàn', en: 'to take an X-ray' },
        { zh: '预防', py: 'yùfáng', en: 'to prevent' },
        { zh: '卫生', py: 'wèishēng', en: 'hygiene' },
        { zh: '肥胖', py: 'féipàng', en: 'obesity' },
        { zh: '糖尿病', py: 'tángniàobìng', en: 'diabetes' },
        { zh: '高血压', py: 'gāoxuèyā', en: 'hypertension' },
        { zh: '癌症', py: 'áizhèng', en: 'cancer' },
        { zh: '心脏病', py: 'xīnzàngbìng', en: 'heart disease' },
        { zh: '流感', py: 'liúgǎn', en: 'influenza' },
        { zh: '肺炎', py: 'fèiyán', en: 'pneumonia' },
        { zh: '过度', py: 'guòdù', en: 'excessive' },
        { zh: '戒烟', py: 'jièyān', en: 'to quit smoking' },
        { zh: '医保', py: 'yībǎo', en: 'medical insurance' },
        { zh: '营养不良', py: 'yíngyǎngbùliáng', en: 'malnutrition' }
      ]
    ]
  },
  {
    id: 'keji',
    name: 'Technology & Online',
    emoji: '💻',
    stages: [
      [
        { zh: '手机', py: 'shǒujī', en: 'mobile phone' },
        { zh: '网', py: 'wǎng', en: 'net' },
        { zh: '网站', py: 'wǎngzhàn', en: 'website' },
        { zh: '上网', py: 'shàngwǎng', en: 'to go online' },
        { zh: '邮件', py: 'yóujiàn', en: 'email' },
        { zh: '密码', py: 'mìmǎ', en: 'password' },
        { zh: '用户', py: 'yònghù', en: 'user' },
        { zh: '文件', py: 'wénjiàn', en: 'file' },
        { zh: '照片', py: 'zhàopiàn', en: 'photograph' },
        { zh: '视频', py: 'shìpín', en: 'video' },
        { zh: '消息', py: 'xiāoxi', en: 'message' },
        { zh: '发', py: 'fā', en: 'to send' },
        { zh: '收', py: 'shōu', en: 'to receive' },
        { zh: '下载', py: 'xiàzài', en: 'to download' },
        { zh: '上传', py: 'shàngchuán', en: 'to upload' },
        { zh: '屏幕', py: 'píngmù', en: 'screen' },
        { zh: '键盘', py: 'jiànpán', en: 'keyboard' },
        { zh: '鼠标', py: 'shǔbiāo', en: 'computer mouse' },
        { zh: '软件', py: 'ruǎnjiàn', en: 'software' },
        { zh: '应用', py: 'yìngyòng', en: 'application' },
        { zh: '搜索', py: 'sōusuǒ', en: 'to search' },
        { zh: '点击', py: 'diǎnjī', en: 'to click' },
        { zh: '充电', py: 'chōngdiàn', en: 'to charge' },
        { zh: '电池', py: 'diànchí', en: 'battery' },
        { zh: '打印', py: 'dǎyìn', en: 'to print' }
      ],
      [
        { zh: '硬件', py: 'yìngjiàn', en: 'hardware' },
        { zh: '系统', py: 'xìtǒng', en: 'system' },
        { zh: '程序', py: 'chéngxù', en: 'program' },
        { zh: '数据', py: 'shùjù', en: 'data' },
        { zh: '网络', py: 'wǎngluò', en: 'network' },
        { zh: '无线', py: 'wúxiàn', en: 'wireless' },
        { zh: '信号', py: 'xìnhào', en: 'signal' },
        { zh: '连接', py: 'liánjiē', en: 'to connect' },
        { zh: '断网', py: 'duànwǎng', en: 'to lose connection' },
        { zh: '登录', py: 'dēnglù', en: 'to log in' },
        { zh: '注册', py: 'zhùcè', en: 'to register' },
        { zh: '账号', py: 'zhànghào', en: 'account name' },
        { zh: '设置', py: 'shèzhì', en: 'settings' },
        { zh: '更新', py: 'gēngxīn', en: 'to update' },
        { zh: '安装', py: 'ānzhuāng', en: 'to install' },
        { zh: '删除', py: 'shānchú', en: 'to delete' },
        { zh: '保存', py: 'bǎocún', en: 'to save' },
        { zh: '备份', py: 'bèifèn', en: 'backup' },
        { zh: '文件夹', py: 'wénjiànjiā', en: 'folder' },
        { zh: '链接', py: 'liànjiē', en: 'hyperlink' },
        { zh: '浏览器', py: 'liúlǎnqì', en: 'browser' },
        { zh: '社交', py: 'shèjiāo', en: 'social' },
        { zh: '评论', py: 'pínglùn', en: 'comment' },
        { zh: '分享', py: 'fēnxiǎng', en: 'to share' },
        { zh: '直播', py: 'zhíbō', en: 'live stream' }
      ],
      [
        { zh: '人工智能', py: 'réngōngzhìnéng', en: 'artificial intelligence' },
        { zh: '算法', py: 'suànfǎ', en: 'algorithm' },
        { zh: '云计算', py: 'yúnjìsuàn', en: 'cloud computing' },
        { zh: '服务器', py: 'fúwùqì', en: 'server' },
        { zh: '数据库', py: 'shùjùkù', en: 'database' },
        { zh: '编程', py: 'biānchéng', en: 'programming' },
        { zh: '代码', py: 'dàimǎ', en: 'code' },
        { zh: '漏洞', py: 'lòudòng', en: 'security hole' },
        { zh: '黑客', py: 'hēikè', en: 'hacker' },
        { zh: '加密', py: 'jiāmì', en: 'encryption' },
        { zh: '隐私', py: 'yǐnsī', en: 'privacy' },
        { zh: '权限', py: 'quánxiàn', en: 'permission' },
        { zh: '带宽', py: 'dàikuān', en: 'bandwidth' },
        { zh: '延迟', py: 'yánchí', en: 'latency' },
        { zh: '接口', py: 'jiēkǒu', en: 'interface' },
        { zh: '版本', py: 'bǎnběn', en: 'version' },
        { zh: '兼容', py: 'jiānróng', en: 'compatible' },
        { zh: '故障', py: 'gùzhàng', en: 'malfunction' },
        { zh: '维护', py: 'wéihù', en: 'maintenance' },
        { zh: '自动化', py: 'zìdònghuà', en: 'automation' },
        { zh: '虚拟', py: 'xūnǐ', en: 'virtual' },
        { zh: '芯片', py: 'xīnpiàn', en: 'chip' },
        { zh: '存储', py: 'cúnchǔ', en: 'storage' },
        { zh: '处理器', py: 'chǔlǐqì', en: 'processor' },
        { zh: '开源', py: 'kāiyuán', en: 'open source' }
      ]
    ]
  },
  {
    id: 'ziran',
    name: 'Nature & Outdoors',
    emoji: '🌲',
    stages: [
      [
        { zh: '山', py: 'shān', en: 'mountain' },
        { zh: '河', py: 'hé', en: 'river' },
        { zh: '海', py: 'hǎi', en: 'sea' },
        { zh: '湖', py: 'hú', en: 'lake' },
        { zh: '树', py: 'shù', en: 'tree' },
        { zh: '花', py: 'huā', en: 'flower' },
        { zh: '草', py: 'cǎo', en: 'grass' },
        { zh: '石头', py: 'shítou', en: 'stone' },
        { zh: '土', py: 'tǔ', en: 'earth' },
        { zh: '沙', py: 'shā', en: 'sand' },
        { zh: '森林', py: 'sēnlín', en: 'forest' },
        { zh: '天空', py: 'tiānkōng', en: 'sky' },
        { zh: '星', py: 'xīng', en: 'star' },
        { zh: '自然', py: 'zìrán', en: 'nature' },
        { zh: '叶子', py: 'yèzi', en: 'leaf' },
        { zh: '根', py: 'gēn', en: 'root' },
        { zh: '种子', py: 'zhǒngzi', en: 'seed' },
        { zh: '田', py: 'tián', en: 'farm field' },
        { zh: '岛', py: 'dǎo', en: 'island' },
        { zh: '海滩', py: 'hǎitān', en: 'beach' },
        { zh: '瀑布', py: 'pùbù', en: 'waterfall' },
        { zh: '山谷', py: 'shāngǔ', en: 'valley' },
        { zh: '泥', py: 'ní', en: 'mud' },
        { zh: '空气', py: 'kōngqì', en: 'air' },
        { zh: '火', py: 'huǒ', en: 'fire' }
      ],
      [
        { zh: '草地', py: 'cǎodì', en: 'meadow' },
        { zh: '沙漠', py: 'shāmò', en: 'desert' },
        { zh: '沼泽', py: 'zhǎozé', en: 'swamp' },
        { zh: '洞穴', py: 'dòngxué', en: 'cave' },
        { zh: '悬崖', py: 'xuányá', en: 'cliff' },
        { zh: '山顶', py: 'shāndǐng', en: 'summit' },
        { zh: '小溪', py: 'xiǎoxī', en: 'brook' },
        { zh: '池塘', py: 'chítáng', en: 'pond' },
        { zh: '海浪', py: 'hǎilàng', en: 'ocean wave' },
        { zh: '潮水', py: 'cháoshuǐ', en: 'tide' },
        { zh: '岸', py: 'àn', en: 'shore' },
        { zh: '树林', py: 'shùlín', en: 'woods' },
        { zh: '枝', py: 'zhī', en: 'branch' },
        { zh: '树干', py: 'shùgàn', en: 'tree trunk' },
        { zh: '果实', py: 'guǒshí', en: 'fruit of a plant' },
        { zh: '玫瑰', py: 'méigui', en: 'rose' },
        { zh: '竹子', py: 'zhúzi', en: 'bamboo' },
        { zh: '松树', py: 'sōngshù', en: 'pine tree' },
        { zh: '柳树', py: 'liǔshù', en: 'willow' },
        { zh: '苔藓', py: 'táixiǎn', en: 'moss' },
        { zh: '蘑菇', py: 'mógu', en: 'mushroom' },
        { zh: '土壤', py: 'tǔrǎng', en: 'soil' },
        { zh: '矿石', py: 'kuàngshí', en: 'ore' },
        { zh: '地球', py: 'dìqiú', en: 'the Earth' },
        { zh: '月球', py: 'yuèqiú', en: 'the Moon' }
      ],
      [
        { zh: '生态', py: 'shēngtài', en: 'ecology' },
        { zh: '环境', py: 'huánjìng', en: 'environment' },
        { zh: '污染', py: 'wūrǎn', en: 'pollution' },
        { zh: '排放', py: 'páifàng', en: 'emissions' },
        { zh: '资源', py: 'zīyuán', en: 'resource' },
        { zh: '能源', py: 'néngyuán', en: 'energy' },
        { zh: '可再生', py: 'kězàishēng', en: 'renewable' },
        { zh: '生物', py: 'shēngwù', en: 'organism' },
        { zh: '栖息地', py: 'qīxīdì', en: 'habitat' },
        { zh: '多样性', py: 'duōyàngxìng', en: 'diversity' },
        { zh: '保育', py: 'bǎoyù', en: 'conservation' },
        { zh: '砍伐', py: 'kǎnfá', en: 'to fell trees' },
        { zh: '荒漠化', py: 'huāngmòhuà', en: 'desertification' },
        { zh: '洪水', py: 'hóngshuǐ', en: 'flood' },
        { zh: '干旱', py: 'gānhàn', en: 'drought' },
        { zh: '地震', py: 'dìzhèn', en: 'earthquake' },
        { zh: '火山', py: 'huǒshān', en: 'volcano' },
        { zh: '海啸', py: 'hǎixiào', en: 'tsunami' },
        { zh: '臭氧', py: 'chòuyǎng', en: 'ozone' },
        { zh: '碳', py: 'tàn', en: 'carbon' },
        { zh: '可持续', py: 'kěchíxù', en: 'sustainable' },
        { zh: '回收', py: 'huíshōu', en: 'to recycle' },
        { zh: '生长', py: 'shēngzhǎng', en: 'to grow' },
        { zh: '繁殖', py: 'fánzhí', en: 'to reproduce' },
        { zh: '海洋', py: 'hǎiyáng', en: 'ocean' }
      ]
    ]
  },
  {
    id: 'jiaoji',
    name: 'Talking to People',
    emoji: '💬',
    stages: [
      [
        { zh: '你好', py: 'nǐhǎo', en: 'hello' },
        { zh: '再见', py: 'zàijiàn', en: 'goodbye' },
        { zh: '谢谢', py: 'xièxie', en: 'thank you' },
        { zh: '不客气', py: 'búkèqi', en: "you're welcome" },
        { zh: '对不起', py: 'duìbuqǐ', en: 'sorry' },
        { zh: '没关系', py: 'méiguānxi', en: 'it does not matter' },
        { zh: '请', py: 'qǐng', en: 'please' },
        { zh: '是的', py: 'shìde', en: 'yes' },
        { zh: '不是', py: 'búshì', en: 'no' },
        { zh: '好的', py: 'hǎode', en: 'all right' },
        { zh: '早上好', py: 'zǎoshanghǎo', en: 'good morning' },
        { zh: '晚安', py: "wǎn'ān", en: 'good night' },
        { zh: '欢迎', py: 'huānyíng', en: 'welcome' },
        { zh: '介绍', py: 'jièshào', en: 'to introduce' },
        { zh: '聊天', py: 'liáotiān', en: 'to chat' },
        { zh: '说话', py: 'shuōhuà', en: 'to talk' },
        { zh: '告诉', py: 'gàosu', en: 'to tell' },
        { zh: '叫', py: 'jiào', en: 'to be called' },
        { zh: '请问', py: 'qǐngwèn', en: 'excuse me' },
        { zh: '打电话', py: 'dǎdiànhuà', en: 'to make a call' },
        { zh: '见面', py: 'jiànmiàn', en: 'to meet' },
        { zh: '一起', py: 'yìqǐ', en: 'together' },
        { zh: '帮忙', py: 'bāngmáng', en: 'to lend a hand' },
        { zh: '祝', py: 'zhù', en: 'to wish' },
        { zh: '客气', py: 'kèqi', en: 'polite' }
      ],
      [
        { zh: '邀请', py: 'yāoqǐng', en: 'to invite' },
        { zh: '拜访', py: 'bàifǎng', en: 'to pay a visit' },
        { zh: '道歉', py: 'dàoqiàn', en: 'to apologize' },
        { zh: '感谢', py: 'gǎnxiè', en: 'to be grateful' },
        { zh: '祝贺', py: 'zhùhè', en: 'to congratulate' },
        { zh: '约会', py: 'yuēhuì', en: 'appointment' },
        { zh: '联系', py: 'liánxì', en: 'to get in touch' },
        { zh: '回复', py: 'huífù', en: 'to reply' },
        { zh: '建议', py: 'jiànyì', en: 'suggestion' },
        { zh: '意见', py: 'yìjiàn', en: 'opinion' },
        { zh: '讨论', py: 'tǎolùn', en: 'to discuss' },
        { zh: '争论', py: 'zhēnglùn', en: 'to argue' },
        { zh: '解释', py: 'jiěshì', en: 'to explain' },
        { zh: '承诺', py: 'chéngnuò', en: 'to promise' },
        { zh: '礼貌', py: 'lǐmào', en: 'politeness' },
        { zh: '尊重', py: 'zūnzhòng', en: 'to respect' },
        { zh: '称呼', py: 'chēnghu', en: 'form of address' },
        { zh: '打招呼', py: 'dǎzhāohu', en: 'to greet' },
        { zh: '握手', py: 'wòshǒu', en: 'to shake hands' },
        { zh: '微笑', py: 'wēixiào', en: 'to smile' },
        { zh: '点头', py: 'diǎntóu', en: 'to nod' },
        { zh: '沉默', py: 'chénmò', en: 'silence' },
        { zh: '表达', py: 'biǎodá', en: 'to express' },
        { zh: '交流', py: 'jiāoliú', en: 'to communicate' },
        { zh: '误会', py: 'wùhuì', en: 'misunderstanding' }
      ],
      [
        { zh: '寒暄', py: 'hánxuān', en: 'small talk' },
        { zh: '客套', py: 'kètào', en: 'polite formalities' },
        { zh: '直率', py: 'zhíshuài', en: 'forthright' },
        { zh: '委婉', py: 'wěiwǎn', en: 'tactful' },
        { zh: '含蓄', py: 'hánxù', en: 'reserved' },
        { zh: '坦白', py: 'tǎnbái', en: 'frank' },
        { zh: '说服', py: 'shuōfú', en: 'to persuade' },
        { zh: '劝', py: 'quàn', en: 'to urge' },
        { zh: '抱怨', py: 'bàoyuàn', en: 'to complain' },
        { zh: '批评', py: 'pīpíng', en: 'to criticize' },
        { zh: '表扬', py: 'biǎoyáng', en: 'to praise' },
        { zh: '夸', py: 'kuā', en: 'to compliment' },
        { zh: '嘲笑', py: 'cháoxiào', en: 'to mock' },
        { zh: '八卦', py: 'bāguà', en: 'gossip' },
        { zh: '谣言', py: 'yáoyán', en: 'rumor' },
        { zh: '秘密', py: 'mìmì', en: 'secret' },
        { zh: '信息', py: 'xìnxī', en: 'information' },
        { zh: '谈判', py: 'tánpàn', en: 'negotiation' },
        { zh: '妥协', py: 'tuǒxié', en: 'compromise' },
        { zh: '冲突', py: 'chōngtū', en: 'conflict' },
        { zh: '和解', py: 'héjiě', en: 'reconciliation' },
        { zh: '面子', py: 'miànzi', en: 'social face' },
        { zh: '关系', py: 'guānxi', en: 'personal connections' },
        { zh: '人情', py: 'rénqíng', en: 'social favor' },
        { zh: '氛围', py: 'fēnwéi', en: 'atmosphere' }
      ]
    ]
  },
  {
    id: 'yundong',
    name: 'Sports & Fitness',
    emoji: '⚽',
    stages: [
      [
        { zh: '运动', py: 'yùndòng', en: 'sport' },
        { zh: '球', py: 'qiú', en: 'ball' },
        { zh: '足球', py: 'zúqiú', en: 'soccer' },
        { zh: '篮球', py: 'lánqiú', en: 'basketball' },
        { zh: '乒乓球', py: 'pīngpāngqiú', en: 'table tennis' },
        { zh: '网球', py: 'wǎngqiú', en: 'tennis' },
        { zh: '游泳', py: 'yóuyǒng', en: 'to swim' },
        { zh: '跑步', py: 'pǎobù', en: 'to jog' },
        { zh: '比赛', py: 'bǐsài', en: 'match' },
        { zh: '队', py: 'duì', en: 'team' },
        { zh: '赢', py: 'yíng', en: 'to win' },
        { zh: '输', py: 'shū', en: 'to lose' },
        { zh: '球队', py: 'qiúduì', en: 'sports team' },
        { zh: '教练', py: 'jiàoliàn', en: 'coach' },
        { zh: '运动员', py: 'yùndòngyuán', en: 'athlete' },
        { zh: '锻炼', py: 'duànliàn', en: 'to work out' },
        { zh: '健身', py: 'jiànshēn', en: 'fitness training' },
        { zh: '跳', py: 'tiào', en: 'to jump' },
        { zh: '踢', py: 'tī', en: 'to kick' },
        { zh: '打球', py: 'dǎqiú', en: 'to play ball' },
        { zh: '分数', py: 'fēnshù', en: 'score' },
        { zh: '冠军', py: 'guànjūn', en: 'champion' },
        { zh: '体育', py: 'tǐyù', en: 'physical education' },
        { zh: '滑雪', py: 'huáxuě', en: 'to ski' },
        { zh: '爬山', py: 'páshān', en: 'to climb a mountain' }
      ],
      [
        { zh: '排球', py: 'páiqiú', en: 'volleyball' },
        { zh: '羽毛球', py: 'yǔmáoqiú', en: 'badminton' },
        { zh: '棒球', py: 'bàngqiú', en: 'baseball' },
        { zh: '高尔夫', py: "gāo'ěrfū", en: 'golf' },
        { zh: '瑜伽', py: 'yújiā', en: 'yoga' },
        { zh: '举重', py: 'jǔzhòng', en: 'weightlifting' },
        { zh: '体操', py: 'tǐcāo', en: 'gymnastics' },
        { zh: '田径', py: 'tiánjìng', en: 'track and field' },
        { zh: '马拉松', py: 'mǎlāsōng', en: 'marathon' },
        { zh: '拳击', py: 'quánjī', en: 'boxing' },
        { zh: '武术', py: 'wǔshù', en: 'martial arts' },
        { zh: '太极', py: 'tàijí', en: 'tai chi' },
        { zh: '滑冰', py: 'huábīng', en: 'ice skating' },
        { zh: '冲浪', py: 'chōnglàng', en: 'surfing' },
        { zh: '潜水', py: 'qiánshuǐ', en: 'diving' },
        { zh: '划船', py: 'huáchuán', en: 'rowing' },
        { zh: '骑马', py: 'qímǎ', en: 'horse riding' },
        { zh: '跳绳', py: 'tiàoshéng', en: 'jump rope' },
        { zh: '俯卧撑', py: 'fǔwòchēng', en: 'push-up' },
        { zh: '拉伸', py: 'lāshēn', en: 'to stretch' },
        { zh: '热身', py: 'rèshēn', en: 'to warm up' },
        { zh: '出汗', py: 'chūhàn', en: 'to sweat' },
        { zh: '体力', py: 'tǐlì', en: 'stamina' },
        { zh: '裁判', py: 'cáipàn', en: 'referee' },
        { zh: '仰卧起坐', py: 'yǎngwòqǐzuò', en: 'sit-up' }
      ],
      [
        { zh: '奥运会', py: 'àoyùnhuì', en: 'the Olympics' },
        { zh: '锦标赛', py: 'jǐnbiāosài', en: 'championship' },
        { zh: '联赛', py: 'liánsài', en: 'league' },
        { zh: '决赛', py: 'juésài', en: 'final round' },
        { zh: '半决赛', py: 'bànjuésài', en: 'semifinal' },
        { zh: '预赛', py: 'yùsài', en: 'preliminary round' },
        { zh: '纪录', py: 'jìlù', en: 'record' },
        { zh: '训练', py: 'xùnliàn', en: 'to train' },
        { zh: '体能', py: 'tǐnéng', en: 'physical conditioning' },
        { zh: '耐力', py: 'nàilì', en: 'endurance' },
        { zh: '爆发力', py: 'bàofālì', en: 'explosive power' },
        { zh: '柔韧', py: 'róurèn', en: 'suppleness' },
        { zh: '协调', py: 'xiétiáo', en: 'coordination' },
        { zh: '战术', py: 'zhànshù', en: 'tactics' },
        { zh: '犯规', py: 'fànguī', en: 'foul' },
        { zh: '罚球', py: 'fáqiú', en: 'penalty shot' },
        { zh: '主场', py: 'zhǔchǎng', en: 'home ground' },
        { zh: '客场', py: 'kèchǎng', en: 'away ground' },
        { zh: '观众', py: 'guānzhòng', en: 'spectators' },
        { zh: '球迷', py: 'qiúmí', en: 'sports fan' },
        { zh: '赞助', py: 'zànzhù', en: 'sponsorship' },
        { zh: '兴奋剂', py: 'xīngfènjì', en: 'performance drug' },
        { zh: '退役', py: 'tuìyì', en: 'to retire from sport' },
        { zh: '业余', py: 'yèyú', en: 'amateur' },
        { zh: '选手', py: 'xuǎnshǒu', en: 'contestant' }
      ]
    ]
  },
  {
    id: 'yishu',
    name: 'Music, Film & Art',
    emoji: '🎬',
    stages: [
      [
        { zh: '音乐', py: 'yīnyuè', en: 'music' },
        { zh: '歌', py: 'gē', en: 'song' },
        { zh: '唱歌', py: 'chànggē', en: 'to sing' },
        { zh: '电影', py: 'diànyǐng', en: 'film' },
        { zh: '画', py: 'huà', en: 'painting' },
        { zh: '画画', py: 'huàhuà', en: 'to draw' },
        { zh: '艺术', py: 'yìshù', en: 'art' },
        { zh: '照相', py: 'zhàoxiàng', en: 'to take a photo' },
        { zh: '乐器', py: 'yuèqì', en: 'musical instrument' },
        { zh: '钢琴', py: 'gāngqín', en: 'piano' },
        { zh: '吉他', py: 'jítā', en: 'guitar' },
        { zh: '鼓', py: 'gǔ', en: 'drum' },
        { zh: '舞蹈', py: 'wǔdǎo', en: 'dance' },
        { zh: '跳舞', py: 'tiàowǔ', en: 'to dance' },
        { zh: '演员', py: 'yǎnyuán', en: 'actor' },
        { zh: '导演', py: 'dǎoyǎn', en: 'director' },
        { zh: '故事', py: 'gùshi', en: 'story' },
        { zh: '小说', py: 'xiǎoshuō', en: 'novel' },
        { zh: '诗', py: 'shī', en: 'poem' },
        { zh: '剧', py: 'jù', en: 'drama' },
        { zh: '舞台', py: 'wǔtái', en: 'stage' },
        { zh: '声音', py: 'shēngyīn', en: 'sound' },
        { zh: '展览', py: 'zhǎnlǎn', en: 'exhibition' },
        { zh: '作品', py: 'zuòpǐn', en: 'artwork' },
        { zh: '书法', py: 'shūfǎ', en: 'calligraphy' }
      ],
      [
        { zh: '交响乐', py: 'jiāoxiǎngyuè', en: 'symphony' },
        { zh: '歌剧', py: 'gējù', en: 'opera' },
        { zh: '京剧', py: 'jīngjù', en: 'Peking opera' },
        { zh: '流行', py: 'liúxíng', en: 'popular' },
        { zh: '摇滚', py: 'yáogǔn', en: 'rock music' },
        { zh: '爵士', py: 'juéshì', en: 'jazz' },
        { zh: '古典', py: 'gǔdiǎn', en: 'classical' },
        { zh: '旋律', py: 'xuánlǜ', en: 'melody' },
        { zh: '节拍', py: 'jiépāi', en: 'beat' },
        { zh: '歌词', py: 'gēcí', en: 'lyrics' },
        { zh: '乐队', py: 'yuèduì', en: 'band' },
        { zh: '歌手', py: 'gēshǒu', en: 'singer' },
        { zh: '作曲', py: 'zuòqǔ', en: 'to compose' },
        { zh: '指挥', py: 'zhǐhuī', en: 'conductor' },
        { zh: '小提琴', py: 'xiǎotíqín', en: 'violin' },
        { zh: '笛子', py: 'dízi', en: 'flute' },
        { zh: '二胡', py: 'èrhú', en: 'erhu' },
        { zh: '油画', py: 'yóuhuà', en: 'oil painting' },
        { zh: '水墨', py: 'shuǐmò', en: 'ink wash' },
        { zh: '雕塑', py: 'diāosù', en: 'sculpture' },
        { zh: '摄影', py: 'shèyǐng', en: 'photography' },
        { zh: '剧本', py: 'jùběn', en: 'screenplay' },
        { zh: '角色', py: 'juésè', en: 'role' },
        { zh: '字幕', py: 'zìmù', en: 'subtitles' },
        { zh: '特效', py: 'tèxiào', en: 'special effects' }
      ],
      [
        { zh: '创作', py: 'chuàngzuò', en: 'to create' },
        { zh: '灵感', py: 'línggǎn', en: 'inspiration' },
        { zh: '风格', py: 'fēnggé', en: 'style' },
        { zh: '流派', py: 'liúpài', en: 'school of art' },
        { zh: '抽象', py: 'chōuxiàng', en: 'abstract' },
        { zh: '写实', py: 'xiěshí', en: 'realistic' },
        { zh: '构图', py: 'gòutú', en: 'composition' },
        { zh: '色彩', py: 'sècǎi', en: 'coloring' },
        { zh: '质感', py: 'zhìgǎn', en: 'texture' },
        { zh: '意境', py: 'yìjìng', en: 'artistic mood' },
        { zh: '象征', py: 'xiàngzhēng', en: 'symbol' },
        { zh: '隐喻', py: 'yǐnyù', en: 'metaphor' },
        { zh: '叙事', py: 'xùshì', en: 'narrative' },
        { zh: '高潮', py: 'gāocháo', en: 'climax' },
        { zh: '结局', py: 'jiéjú', en: 'ending' },
        { zh: '评论家', py: 'pínglùnjiā', en: 'critic' },
        { zh: '票房', py: 'piàofáng', en: 'box office' },
        { zh: '首映', py: 'shǒuyìng', en: 'premiere' },
        { zh: '获奖', py: 'huòjiǎng', en: 'to win an award' },
        { zh: '提名', py: 'tímíng', en: 'nomination' },
        { zh: '版权', py: 'bǎnquán', en: 'copyright' },
        { zh: '原创', py: 'yuánchuàng', en: 'original' },
        { zh: '改编', py: 'gǎibiān', en: 'adaptation' },
        { zh: '纪录片', py: 'jìlùpiàn', en: 'documentary' },
        { zh: '即兴', py: 'jíxìng', en: 'improvised' }
      ]
    ]
  },
  {
    id: 'zhengfu',
    name: 'Government, Law & News',
    emoji: '🏛️',
    stages: [
      [
        { zh: '政府', py: 'zhèngfǔ', en: 'government' },
        { zh: '法律', py: 'fǎlǜ', en: 'law' },
        { zh: '新闻', py: 'xīnwén', en: 'news' },
        { zh: '报纸', py: 'bàozhǐ', en: 'newspaper' },
        { zh: '警察', py: 'jǐngchá', en: 'police' },
        { zh: '总统', py: 'zǒngtǒng', en: 'president' },
        { zh: '选举', py: 'xuǎnjǔ', en: 'election' },
        { zh: '投票', py: 'tóupiào', en: 'to vote' },
        { zh: '公民', py: 'gōngmín', en: 'citizen' },
        { zh: '权利', py: 'quánlì', en: 'a right' },
        { zh: '规则', py: 'guīzé', en: 'rule' },
        { zh: '禁止', py: 'jìnzhǐ', en: 'to forbid' },
        { zh: '允许', py: 'yǔnxǔ', en: 'to allow' },
        { zh: '法院', py: 'fǎyuàn', en: 'court' },
        { zh: '官员', py: 'guānyuán', en: 'official' }
      ],
      [
        { zh: '议会', py: 'yìhuì', en: 'parliament' },
        { zh: '政党', py: 'zhèngdǎng', en: 'political party' },
        { zh: '政策', py: 'zhèngcè', en: 'policy' },
        { zh: '法案', py: "fǎ'àn", en: 'legislative bill' },
        { zh: '宪法', py: 'xiànfǎ', en: 'constitution' },
        { zh: '条约', py: 'tiáoyuē', en: 'treaty' },
        { zh: '签署', py: 'qiānshǔ', en: 'to sign' },
        { zh: '律师', py: 'lǜshī', en: 'lawyer' },
        { zh: '法官', py: 'fǎguān', en: 'judge' },
        { zh: '陪审团', py: 'péishěntuán', en: 'jury' },
        { zh: '证据', py: 'zhèngjù', en: 'evidence' },
        { zh: '证人', py: 'zhèngrén', en: 'witness' },
        { zh: '审判', py: 'shěnpàn', en: 'trial' },
        { zh: '判决', py: 'pànjué', en: 'verdict' },
        { zh: '上诉', py: 'shàngsù', en: 'to appeal' },
        { zh: '罚款', py: 'fákuǎn', en: 'a fine' },
        { zh: '监狱', py: 'jiānyù', en: 'prison' },
        { zh: '逮捕', py: 'dàibǔ', en: 'to arrest' },
        { zh: '起诉', py: 'qǐsù', en: 'to prosecute' },
        { zh: '辩护', py: 'biànhù', en: 'to defend in court' },
        { zh: '记者', py: 'jìzhě', en: 'journalist' },
        { zh: '采访', py: 'cǎifǎng', en: 'to interview' },
        { zh: '报道', py: 'bàodào', en: 'to report on' },
        { zh: '媒体', py: 'méitǐ', en: 'media' },
        { zh: '头条', py: 'tóutiáo', en: 'headline' }
      ],
      [
        { zh: '民主', py: 'mínzhǔ', en: 'democracy' },
        { zh: '主权', py: 'zhǔquán', en: 'sovereignty' },
        { zh: '外交', py: 'wàijiāo', en: 'diplomacy' },
        { zh: '制裁', py: 'zhìcái', en: 'sanction' },
        { zh: '联盟', py: 'liánméng', en: 'alliance' },
        { zh: '腐败', py: 'fǔbài', en: 'corruption' },
        { zh: '透明', py: 'tòumíng', en: 'transparency' },
        { zh: '问责', py: 'wènzé', en: 'accountability' },
        { zh: '舆论', py: 'yúlùn', en: 'public opinion' },
        { zh: '言论', py: 'yánlùn', en: 'speech' },
        { zh: '审查', py: 'shěnchá', en: 'censorship' },
        { zh: '抗议', py: 'kàngyì', en: 'to protest' },
        { zh: '示威', py: 'shìwēi', en: 'demonstration' },
        { zh: '罢工', py: 'bàgōng', en: 'strike' },
        { zh: '改革', py: 'gǎigé', en: 'reform' },
        { zh: '立法', py: 'lìfǎ', en: 'legislation' },
        { zh: '执法', py: 'zhífǎ', en: 'law enforcement' },
        { zh: '司法', py: 'sīfǎ', en: 'judiciary' },
        { zh: '行政', py: 'xíngzhèng', en: 'administration' },
        { zh: '补贴', py: 'bǔtiē', en: 'subsidy' },
        { zh: '福利', py: 'fúlì', en: 'welfare' },
        { zh: '难民', py: 'nànmín', en: 'refugee' },
        { zh: '人权', py: 'rénquán', en: 'human rights' },
        { zh: '公正', py: 'gōngzhèng', en: 'justice' },
        { zh: '社论', py: 'shèlùn', en: 'editorial' }
      ]
    ]
  },
  {
    id: 'anquan',
    name: 'Safety & Trouble',
    emoji: '🚨',
    stages: [
      [
        { zh: '小心', py: 'xiǎoxīn', en: 'careful' },
        { zh: '帮助', py: 'bāngzhù', en: 'help' },
        { zh: '火灾', py: 'huǒzāi', en: 'fire disaster' },
        { zh: '事故', py: 'shìgù', en: 'accident' },
        { zh: '偷', py: 'tōu', en: 'to steal' },
        { zh: '小偷', py: 'xiǎotōu', en: 'thief' },
        { zh: '丢', py: 'diū', en: 'to lose' },
        { zh: '麻烦', py: 'máfan', en: 'trouble' },
        { zh: '错', py: 'cuò', en: 'wrong' },
        { zh: '救', py: 'jiù', en: 'to rescue' },
        { zh: '喊', py: 'hǎn', en: 'to shout' },
        { zh: '逃', py: 'táo', en: 'to flee' },
        { zh: '伤', py: 'shāng', en: 'injury' },
        { zh: '撞', py: 'zhuàng', en: 'to collide' },
        { zh: '摔', py: 'shuāi', en: 'to fall over' },
        { zh: '急', py: 'jí', en: 'urgent' },
        { zh: '灭火器', py: 'mièhuǒqì', en: 'fire extinguisher' },
        { zh: '报警', py: 'bàojǐng', en: 'to call the police' },
        { zh: '安全带', py: 'ānquándài', en: 'seat belt' },
        { zh: '出口', py: 'chūkǒu', en: 'exit' }
      ],
      [
        { zh: '紧急', py: 'jǐnjí', en: 'emergency' },
        { zh: '警报', py: 'jǐngbào', en: 'alarm' },
        { zh: '危机', py: 'wēijī', en: 'crisis' },
        { zh: '风险', py: 'fēngxiǎn', en: 'risk' },
        { zh: '预警', py: 'yùjǐng', en: 'early warning' },
        { zh: '避难', py: 'bìnàn', en: 'to take refuge' },
        { zh: '疏散', py: 'shūsàn', en: 'to evacuate' },
        { zh: '求救', py: 'qiújiù', en: 'to call for help' },
        { zh: '抢劫', py: 'qiǎngjié', en: 'robbery' },
        { zh: '骗子', py: 'piànzi', en: 'swindler' },
        { zh: '诈骗', py: 'zhàpiàn', en: 'fraud' },
        { zh: '暴力', py: 'bàolì', en: 'violence' },
        { zh: '吵架', py: 'chǎojià', en: 'to quarrel' },
        { zh: '打架', py: 'dǎjià', en: 'to come to blows' },
        { zh: '损失', py: 'sǔnshī', en: 'loss' },
        { zh: '赔偿', py: 'péicháng', en: 'compensation' },
        { zh: '破坏', py: 'pòhuài', en: 'to damage' },
        { zh: '警告', py: 'jǐnggào', en: 'to warn' },
        { zh: '防止', py: 'fángzhǐ', en: 'to prevent' },
        { zh: '安全帽', py: 'ānquánmào', en: 'safety helmet' }
      ],
      [
        { zh: '隐患', py: 'yǐnhuàn', en: 'hidden danger' },
        { zh: '防范', py: 'fángfàn', en: 'to guard against' },
        { zh: '应急', py: 'yìngjí', en: 'emergency response' },
        { zh: '演习', py: 'yǎnxí', en: 'drill' },
        { zh: '救援', py: 'jiùyuán', en: 'rescue' },
        { zh: '幸存', py: 'xìngcún', en: 'to survive' },
        { zh: '伤亡', py: 'shāngwáng', en: 'casualties' },
        { zh: '遇难', py: 'yùnàn', en: 'to perish' },
        { zh: '灾难', py: 'zāinàn', en: 'disaster' },
        { zh: '爆炸', py: 'bàozhà', en: 'explosion' },
        { zh: '泄漏', py: 'xièlòu', en: 'to leak' },
        { zh: '中毒', py: 'zhòngdú', en: 'poisoning' },
        { zh: '窒息', py: 'zhìxī', en: 'suffocation' },
        { zh: '溺水', py: 'nìshuǐ', en: 'drowning' },
        { zh: '触电', py: 'chùdiàn', en: 'electric shock' },
        { zh: '防护', py: 'fánghù', en: 'protection' },
        { zh: '监控', py: 'jiānkòng', en: 'surveillance' },
        { zh: '巡逻', py: 'xúnluó', en: 'patrol' },
        { zh: '保安', py: "bǎo'ān", en: 'security guard' },
        { zh: '嫌疑', py: 'xiányí', en: 'suspicion' },
        { zh: '犯罪', py: 'fànzuì', en: 'crime' },
        { zh: '罪犯', py: 'zuìfàn', en: 'criminal' },
        { zh: '受害者', py: 'shòuhàizhě', en: 'victim' },
        { zh: '报案', py: "bào'àn", en: 'to report a case' },
        { zh: '善后', py: 'shànhòu', en: 'to deal with the aftermath' }
      ]
    ]
  },
];

/** The progress key for a word. One function so nothing hardcodes the field. */
export function wordId(word) {
  return word.zh;
}

export function getDeck(deckId) {
  return DECKS.find((deck) => deck.id === deckId) ?? null;
}

export function stageWords(deckId, stage) {
  if (deckId === ALL_DECK_ID) return DECKS.flatMap((deck) => deck.stages[stage] ?? []);
  return getDeck(deckId)?.stages[stage] ?? [];
}

export function deckWords(deckId) {
  return Array.from({ length: STAGE_COUNT }, (_, stage) => stageWords(deckId, stage)).flat();
}

/** Every distinct word in the app, deduped by key across decks. */
export function allWords() {
  const seen = new Map();
  for (const deck of DECKS) {
    for (const word of deck.stages.flat()) {
      if (!seen.has(word.zh)) seen.set(word.zh, word);
    }
  }
  return [...seen.values()];
}

/** The word record for a key, or null. */
export function findWord(zh) {
  return allWords().find((word) => word.zh === zh) ?? null;
}
